### ISSUE TITLE
PROYECTOS. Agregar el nombre del proyecto que se está editando

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#109]
La única forma de averiguar el nombre del proyecto en edición es volviendo al menu general. 
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/3cb5917c-3c65-49e4-920c-2b6b4ef83a5c)

**Comment by jvillegas88** [comment]
Modificado:
![image](https://user-images.githubusercontent.com/36643035/78299742-c8f86200-750c-11ea-8363-c7d951dbf3cc.png)

**Comment by jvillegas88** [comment]
### Horas de producción: 0:11
