### ISSUE TITLE
SERVIDORES. Gestionar los dominios de los servidores staging y production

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#150]
Se necesita un nuevo dominio para poder gestionar los subdominios de `tomate2000` e `iscamen` en staging del mismo modo que se hace en producción.

**Comment by asergiop21** [comment]
Le solicite a Julian que lo diera de alta en nic.ar a si puedo seguir con Ardengo

**Comment by jvillegas88** [comment]
Se decidió mantener el dominio `www.geoworks.com.ar` para el servidor de `staging` y utilizar el dominio `www.gisworking.com` para el servidor de `production`.

La idea es que lo usuarios accedan a la aplicación a través de la página web de _Gisworking_, del mismo modo que actualmente lo hace _Inciti_
