### ISSUE TITLE
ATRIBUTOS. Mostrar el campo ID en los Atributos del proyecto

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#153]
El campo `id` es utilizado por @flaviaarias en **Gw_lite** para identificar el campo `subtítulo` y poder mostrarlo/ocultarlo.

Mostrar el `id` a los usuarios finales puede no ser una buena opción, por lo que una vez que se implementen los roles (#87), esta columna solo será visible para `superadmin`

**Comment by asergiop21** [comment]
Se agregó el id al los atributos

**Comment by asergiop21** [comment]
Se agregó los id en los registros hijos. 
![Captura de pantalla de 2020-03-03 10-53-37.png](https://images.zenhubusercontent.com/5b2a5abf2f27e82b33e6b336/f0338c99-fd79-4945-b506-348a40603d21)
**Hora: 30 minutos**

**Comment by jvillegas88** [comment]
### Horas de producción: 0,5
