### ISSUE TITLE
BS4. Migrar pantalla "Listados"

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#159]
Antes:
![image](https://user-images.githubusercontent.com/36643035/71769916-7acfc480-2f05-11ea-9a2e-e4b1ba399ca7.png)

**Comment by JChambu** [comment]
Migrar de dónde a dónde??

**Comment by jvillegas88** [comment]
Agregar la flecha para volver atrás.

**Comment by jvillegas88** [comment]
### **Horas de producción: 0:56**
