### ISSUE TITLE
ISCAMEN. CAMPOS DUPLICADOS

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#175]
no andan los indicadores numericos porque hay campos dupolicados

**Comment by jvillegas88** [comment]
Este error surgió cuando se agregaron las trampas de datos de Carpocapsa y Grafolita (issue #112). Como la aplicación no está preparada para que se carguen datos sobre un proyecto que ya existe, sino para que se genere un proyecto nuevo desde un archivo, al no coincidir algunas de las cabeceras se duplicaron los campos del proyecto.

**Comment by jvillegas88** [comment]
### No se cobró por esta issue
