### ISSUE TITLE
ZENHUB. Mejores Practicas. Clasificar separadamente los issues cerrados y pagados con fines adminsitrativos

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#210]
Esto fue discutido con Jonatan, para separar los issues cerrados (desarrollados y testeados) de los cerrados, testeados y pagados.

**Comment by jvillegas88** [comment]
Se implementó la siguiente organización:

- **New Issues**: Pipeline por defecto al que se agregan todas las issues al momento de crearse. 
- **Epics**: Grandes tareas que engloban issues más pequeñas.
- **Icebox**: Issues que no se van a realizar por el momento.
- **Backlog**: Issues que se van realizar, pero aún no se les asigna un sprint.
- **Next Sprint**: Issues que se van a realizar la próxima semana.
- **Current Sprint**: Issues que se van a realizar la semana en curso.
- **In Progress**: Issues en las que se está trabajando actualmente.
- **Committed**: Issues terminadas y subidas al repositorio.
- **Staging**: Issues deployadas en el servidor de staging disponibles para ser testeadas.
- **Done**: Issues terminadas listas para facturar a fin de mes.
- **Closed**: Issues cobradas

**Comment by jvillegas88** [comment]
### El tiempo de producción de esta issue se incluyó en las tareas de administración del mes de enero, más presisamente en las tareas realizadas el día 6/01/2020
