### ISSUE TITLE
USUARIOS. Automatizar la generación del authentication_token al crear un usuario

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#213]
El `authentication_token` es utilizado solo para permitir el acceso en `gw_lite`, por este motivo los usuarios recién creados no pueden acceder a `gw_lite`, pero si a `geoworks`.

Los `authentication_token` se estaban creando manualmente cada vez que se generaba un usuario nuevo.

Captura:
![image](https://user-images.githubusercontent.com/36643035/76113480-fb24ab80-5fc2-11ea-8803-4c211652fc60.png)

**Comment by asergiop21** [comment]
Se modificó la creación del usuario para que se autogenere el token.
**Hora: 1**

**Comment by jvillegas88** [comment]
Se quitó el label de bug y se modificó el título para que correspondiera con el trabajo realizado
