### ISSUE TITLE
MAPA DE CALOR. Cuando tengo un filtro activado el mapa de calor no funciona

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#215]
@JChambu dijo:
> Bug: Cuando haces un filtro, ejemplo comuna=providencia; luego el HeatMap no funciona

Captura:
![image](https://user-images.githubusercontent.com/36643035/72179920-bf0b0b00-33c4-11ea-99c5-c43e76bb6f1f.png)

**Comment by asergiop21** [comment]
Se elimino el conflico con la tabla project_data_children

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461377-b9a91e00-769e-11ea-8967-d4e6bf80b34a.png)
