### ISSUE TITLE
ATRIBUTOS. Humanizar el 'key' que se genera a partir del 'name' de cada atributo

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#226]
Cada atributo del proyecto tiene un nombre (`name`), a partir de ese nombre se genera un `key` que identifica al atributo para que luego si se desea modificar el nombre no genere problema. Si el `name` contiene signos, espacios, etc esto genera un error en el `key`, por lo que se deben limpiar esos caracteres y dejarlos solo con letras y guiones bajos, a este proceso se lo conoce como humanización.

**Comment by asergiop21** [comment]
Se agregó expresión regular para eliminar caracteres especiales en la columna key de los campos.
**Horas: 45 minutos**
