### ISSUE TITLE
DATABASE. Generar script para modificar todos los 'key' de todas las corporaciones

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#227]
Cada atributo del proyecto tiene un nombre (`name`), a partir de ese nombre se genera un `key` que identifica al atributo para que luego si se desea modificar el nombre no genere problema. Los `key` que se generaron anteriormente no estaban humanizados, por lo que contenían signos, espacios, etc que generan un problema. Esto se va a solucionar con la humanización del `key` de los `atributos` (issue #226), pero ahora necesitamos arreglar todos los registros que ya están cargados en la base de datos.

**Comment by jvillegas88** [comment]
Corporaciones en las que ya está solucionado:

- [ ] Iscamen
- [ ] Tomate2000
- [ ] Andariego
- [ ] AVA

**Comment by asergiop21** [comment]
Se modifico los key que estaban erroneos en la tabla de project_fields, también se actualizaron todo los key almacenados en la tabla projects.

**hora: 4.5 horas**
