### ISSUE TITLE
ROLES. Crashea al intentar crear un rol

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#235]
Opciones seleccionadas:
![image](https://user-images.githubusercontent.com/36643035/73657706-95669c00-4671-11ea-950d-31ae9353c854.png)

Error:
![image](https://user-images.githubusercontent.com/36643035/73657633-6d773880-4671-11ea-9ef8-9737d7f284dc.png)

Se testeo en las corporaciones Andariego y Tomatate2000

**Comment by jvillegas88** [comment]
@asergiop21 falta documentar que fue lo que generó el `bug` y si la solución es momentánea o final.

**Comment by asergiop21** [comment]
al  unificar las tablas Events y Model_types al esquema publico, los foreign key  de la tabla permisos no cumplen su función por ende se tuvieron que borrar, esto se tuvo que hacer para la tarea de los seed en docker. 
Horas: **45 minutos**
