### ISSUE TITLE
ANDARIEGO. Cuando se intenta eliminar un atributo la aplicación crashea (error: key)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#238]
Error:
![image](https://user-images.githubusercontent.com/36643035/73662271-483af800-467a-11ea-8c53-0162b99c6f5c.png)

**Comment by jvillegas88** [comment]
Solucionado. Este bug surgió debido a que la issue #227 no está terminada, solo se habían arreglado las corporaciones `tomate2000` e `iscamen`.

**Comment by asergiop21** [comment]
Se arregló manualmente.
**Horas: 30 minutos**
