### ISSUE TITLE
ANDARIEGO. Cuando se intenta crear un nuevo proyecto crashea (error: corporación mal creada)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#239]

**Comment by jvillegas88** [comment]
Solucionado. El error estaba en que se duplicaban las [SEQUENCE](https://www.postgresql.org/docs/8.1/functions-sequence.html) debido a que este proyecto fue clonado. Esto quedará solucionado definitivamente una vez que se desarrolle la parte de clonar corporaciones (#232)

**Comment by asergiop21** [comment]
Se reviso en todas las corporaciones creadas
**Horas: 30 minutos**
