### ISSUE TITLE
INTERFAZ. Ordenar alfabéticamente todos los listados

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#242]
Listados a ordenar: 

- [x] Proyectos (navbar)
- [x] Campo (modal Indicadores)
- [x] Agrupar (modal Indicadores)
- [x] Tipo de gráfico (modal Gráficos)
- [x] Indicador (modal Gráficos)
- [x] Campo (modal Filtro)
- [x] Valor (modal Filtro)
- [x] Campos (modal Mapa de Calor)
- [x] KPI (modal Mapa de Calor)
- [x] Campo (modal Colorear Puntos)

**Comment by jvillegas88** [comment]
Todos los `select` de la descripción están ordenados alfabéticamente en Geoworks

**Comment by asergiop21** [comment]
**Hora: 1**
