### ISSUE TITLE
TOMATE2000. Al filtrar por app_usuario y app_estado en el proyecto Muestreos no trae los puntos (error: con key y vista geoserver)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#247]
Se testeó solo en la corporación `Tomate2000`, el único proyecto que arrojó este error es `Muestreos`

Captura filtro `app_usuarios = Matias Buso`:

![image](https://user-images.githubusercontent.com/36643035/73882916-be3d8b80-4841-11ea-9879-9c375264ed16.png)

Captura filtro `app_estado = default`:

![image](https://user-images.githubusercontent.com/36643035/73882879-a403ad80-4841-11ea-9673-966764e2bad8.png)

**Comment by jvillegas88** [comment]
Ya trae los puntos correctamente:
![image](https://user-images.githubusercontent.com/36643035/74879351-b1dc2700-5347-11ea-937e-375dca2e5f37.png)

**Comment by jvillegas88** [comment]
@asergiop21 falta documentar porque surgió este bug y si la solución es final o momentánea.

**Comment by asergiop21** [comment]
Se recreo nuevamente la vista y actualizó geoserver.
**Horas: 30 minutos**
