### ISSUE TITLE
TOMATE2000. Cargar 2 registros en la base de datos para el proyecto 'Muestreos'

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#262]
**Regsitro 1:**
_Productor_: Sánchez, Manuel
_Fecha Muestra_: 28/1/2020
_N° de Pool_: 35
_N° de Precinto:_ 727039
_Código de muestreo_: SM-L3-H7709-200128-039
_Ubicación_: https://goo.gl/maps/meypg2SUpWaMG3wZ7

**Regsitro 2:**
_Productor_: Canchi, Victor
_Fecha Muestra_: 28/1/2020
_N° de Pool_: 35
_N° de Precinto_: 727041
_Código de muestreo_: CV-L1-H7709-200128-041
_Ubicación_: https://maps.google.com?q=-33.5308471,-69.1156323&hl=es-AR&gl=ar

**Comment by asergiop21** [comment]
Se Ingresaron los 2 registros a tomate2000 muestreos, lo único que hay que cambiar a que usuario pertenecen estos registros.

**Comment by asergiop21** [comment]
Se actualizaron los registros con el user_id = 114

**Comment by jvillegas88** [comment]
### Horas de producción: 0,5
