### ISSUE TITLE
RECORRIDO. Permitir habilitar/deshabilitar como recorrido un proyecto

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#263]
Se decidió trabajar los datos de recorridos como un proyecto más, por lo que se deberá agregar un `checkbox` para permitir habilitar un proyecto como recorrido desde la pantalla Nuevo/Editar Proyecto

**Comment by asergiop21** [comment]
Se agrego en nuevo/editar proyecto un checkbox con el nombre recorrido.

**Comment by asergiop21** [comment]
**Hora: 1**
