### ISSUE TITLE
ANDARIEGO. Los popups no traen los datos, llega un error de geoserver (error: no recarga vista geoserver)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#264]
Error:
![image](https://user-images.githubusercontent.com/36643035/74166816-04aa3600-4c06-11ea-8a48-4293267d8680.png)

Captura de lo que aparentemente llega en el objeto y no se puede parsear:
![image](https://user-images.githubusercontent.com/36643035/74166744-e17f8680-4c05-11ea-8d86-6852370a9d65.png)

**Comment by jvillegas88** [comment]
Ya funciona correctamente el popup en Andariego:
![image](https://user-images.githubusercontent.com/36643035/74879642-5199b500-5348-11ea-8421-4519b54c1211.png)

**Comment by jvillegas88** [comment]
La solución a esta issue fue temporal ya que se recargó la vista de `geoserver` manualmente, esto no debería volver a ocurrir cuando se complete la issue #283

**Comment by asergiop21** [comment]
Se realizo nuevamente la vista en postgres y se recargo geoserver manualmente
**Hora: 30 minutos**
