### ISSUE TITLE
CORPORACIONES. Crear 6 corporaciones manualmente

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#266]
Se necesita que se copien los `Listados` de `tomate2000` a las nuevas corporaciones. El resto de los módulos deben estar vacíos.

Corporaciones:

- [x] TODO AGRO S.A. 
- [x] TECH AGRO
- [x] AGQ Agroconciencia
- [x] SChT San Juan
- [x] IDC Mendoza
- [x] La Campagnola (ARCOR)

**Comment by asergiop21** [comment]
Se generaron 6 corporaciones nuevas, con listados migrados desde tomate2000. se detallan url:
http://lacampagnola.geoworks.com.ar/es
http://techagro.geoworks.com.ar/es
http://idc.geoworks.com.ar/es
http://scht.geoworks.com.ar/es
http://todoagro.geoworks.com.ar/es
http://agq.geoworks.com.ar/es

**Comment by jvillegas88** [comment]
Algunas de las últimas corporaciones creadas están caídas:
- [ ] `techagro`
- [ ] `lacampagnola`
- [ ] `idc`
- [ ] `scht`
- [ ] `agq`

Capturas:
![image](https://user-images.githubusercontent.com/36643035/74882319-a12eaf80-534d-11ea-888c-0ff4249e4b6e.png)
![image](https://user-images.githubusercontent.com/36643035/74882333-a7249080-534d-11ea-8141-e49a335f88e1.png)
![image](https://user-images.githubusercontent.com/36643035/74882342-ad1a7180-534d-11ea-97a9-2b6ca6a04429.png)
![image](https://user-images.githubusercontent.com/36643035/74882350-b277bc00-534d-11ea-9640-7230444d747e.png)
![image](https://user-images.githubusercontent.com/36643035/74882358-b7d50680-534d-11ea-911e-60160b598cde.png)

Se vuelve a _Current Sprint_

**Comment by asergiop21** [comment]
Se modificaron los valores de secuencias y se testeo que estén funcionando. 
**horas: 4.5**
