### ISSUE TITLE
USUARIOS. Generar lógica para que se puedan filtrar los registros por owner

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#271]
Este filtro permitirá que cada usuario pueda ver solamente lo que él creó. En cuanto a `gw_lite`, si tiene aplicado el filtro owner, sólo sincronizará los registros que le pertenecen.

**Comment by asergiop21** [comment]
Se desarrollo en aplicación para que los usuarios con owner = true solo puedan ver sus registros
