### ISSUE TITLE
GEOSERVER. Las vistas no se están recargando automáticamente

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#283]
Cuando se modifica el prototipo de un proyecto, la vista de `geoserver` se debería actualizar para incluir los nuevos `campos`. Esto no está sucediendo y trae problemas con los `popups`, donde el dato llega `undefined`.

**Comment by asergiop21** [comment]
Se cambio el nombre del parámetro que se pasa para validar si existe o no una capa en geoserver, en el caso de que exista esto llama a la función de recargar la capa en geoserver. 
 Antes se pasaba el atributo "name",ahora se pasa el atributo "name_layer", ya que este no sufre modificaciones.
Revisión, modificación, testeo.
**Hora: 1**
