### ISSUE TITLE
AVA. El usuario superadmin no puede ver algunas acciones (error: corporación mal creada)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#284]
Captura:
![image](https://user-images.githubusercontent.com/36643035/74881443-17321700-534c-11ea-8de3-1fdbf32a99b4.png)

Como podemos observar, no figura el icono de Indicadores, ni figuran los indicadores de texto.

**Comment by asergiop21** [comment]
Se modificó el rol para poder ver el resto de las acciones, también se le agregó en los atributos el tipo de campo. 
**Hora: 20 minutos**
