### ISSUE TITLE
DEMO. El proyecto Telco Regional no trae los gráficos ni el time slider (error: campos de indicadores almacena 0)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#287]
@LHR1971 dijo:

> Hay un bug en geoworks, que es dificil de replicar pero se los trato de explicar.:  En un proyecto (lo hice en telco regional) que ya tenía algunos gráficos hechos, quise hacer un gráfico y al parecer el gráfico no estaba bien diseñado...... al intentarlo graficar, no solo que no me lo grafico, sino que me desaparecieron todos los que ya estaban hechos................ lo dejé así para que puedas entrar y verlo personalmente......... el grafico que rompió todo fue " Celulares Activos" por cliente.

Captura:
![image](https://user-images.githubusercontent.com/36643035/74938714-49d02400-53cd-11ea-9c07-5aa0324a8704.png)

**Comment by asergiop21** [comment]
Se agrego una función independiente para los campos de tipos selección en los indicadores, ya que la misma función se ocupa en la herramienta para filtras y genera problemas. 
**Horas: 1 **
