### ISSUE TITLE
SERVIDOR. Error al modificar estructuras de todoagro (error: servidor lleno)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#296]
@JChambu dijo:

> ok, no puedo modificar estructuras en Todo Agro de Geoworks
> que paso? estan tocando el server? avisen si estan haciendo mantenimiento,no puedo hacer nada
> sisi, Geoworks conecta pero no guarda, me sale el cartel de We are sorry
> jony, estara caido el sevidor? podras
> Revisar?

**Comment by jvillegas88** [comment]
El problema era que el servidor estaba lleno:
![image](https://user-images.githubusercontent.com/36643035/75694644-a2ce7080-5c87-11ea-8b1c-c0f5c4ac8a9f.png)

**Comment by asergiop21** [comment]
Se accedió al server, se busco los registros que mas ocupan ( logs) y se vaciaron
**Horas: 30 minutos**

**Comment by jvillegas88** [comment]
### Horas de producción:

@jvillegas88: 0:24 hs (Realizar pruebas y detectar el error )
@asergiop21: 0:30 hs (Buscar registros que ocupaban mas espacio y vaciarlos)
