### ISSUE TITLE
ATRIBUTOS. Incluir los campos app_id, app_usuario y app_estado por defecto en cada proyecto

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#304]

**Comment by asergiop21** [comment]
Se muestran los campos app_id, app_usuario, app_estado al comienzo de un nuevo proyecto con los items (nombre, hidden, y tipo de campo). Se agregó validación de que los campos sean únicos por cada proyecto, que exista el nombre del proyecto y el tipo de geometría del proyecto. 
**Horas: 8 horas**
