### ISSUE TITLE
USUARIOS. Cuando se crea un usuarios no se le asigna el rol correspondiente

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#308]
En la tabla `user_customers` se guarda el valor `0`:

![image](https://user-images.githubusercontent.com/36643035/76114294-8488ad80-5fc4-11ea-8869-7e8b5d3e6b58.png)

**Comment by asergiop21** [comment]
Se corrigió el parámetro que estaba llegando en el rol_id

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461529-2bce3280-76a0-11ea-8179-a034b55fb241.png)
