### ISSUE TITLE
AMANDES. Actualizar la corporación con los cambios de la aplicación

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#309]
Se actualizaron:
- dar de alta usuario superadmin
- roles
- estados
- funciones geométricas

**Comment by asergiop21** [comment]
Se aplicaron las actualizaciones correspondiente a la corporación Amandes. 

- dar de alta usuario superadmin
- roles
- estados
- funciones geométrica

**Hora: 30 minutos**
