### ISSUE TITLE
CORPORACIÓN. Permitir que cada corporación tenga su propio datastore en geoserver para almacenamiento

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#310]
Se detectó ya que la corporación `amandes` tiene un proyectos llamado `propiedades` y trae los mismos datos de la corporación `tomate2000`. Probablemente el problema sea que geoserver no está discriminando los `datastore`

@JChambu dijo: 
> Ni bien guardar el proyecto Propiedades, y agregando los campos convencionales, al guardar me trae todos las propiedades de tomate2000- Esto puede ser porque cuando creamos amandes lo hicimos como copia de tomate 2000' para heredar su  modelo de datos. Sin embargo, si es asi no puedo ver sus proyectos. Habria que borrar todo proyecto existente en esta corporacion-

**Comment by asergiop21** [comment]
Se modifico la estructura en la creación de capas de  geoserver agregando el almacenamiento y se agregó dicho alamacenamiento en leaflet para la lectura
