### ISSUE TITLE
MAPA. Validar que no se muestren los registros inactivos (eliminados)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#313]
Existen algunos registros que se han eliminado, pero teniendo en cuenta que la eliminación es lógica, se debe validar para que sólo se muestren en el dashboard los registros con `row_active = true`. Esto ya está funcionando en `gw_lite`.

Ejemplo de registro eliminado que se ve en `geoworks`:

![image](https://user-images.githubusercontent.com/36643035/76257160-eb5dcf00-622f-11ea-99d1-88b86ba5d536.png)

**Comment by asergiop21** [comment]
Se colocaron condicion sobre los registros que estan activo
