### ISSUE TITLE
INDICADORES. Refactory del módulo indicadores

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#324]
El refactory del módulo `Indicadores` busca eliminar todos los errores que existen en el módulo aparte de ordenar su código, esto incluye:

- Modularizar el código
- Unificar funciones
- Validar tipos de campos

**Comment by jvillegas88** [comment]
Falta:

- [ ] Agregar campos requeridos: `Análisis` y `Campo` en indicadores simples
- [ ] Agregar campos requeridos: `Sentencia` en indicadores avanzados

**Comment by asergiop21** [comment]
Se agregaron validaciones a esos campos y se refactorizó el modulo completo de indicadores
