### ISSUE TITLE
MAPA. No funciona el popup al incluir el atributo app_id

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#329]
Estoy en Amandes. Proyecto Cuadro Productivo. Tengo 3 registros para desactivar, quiero saber el app_id. Al mostrarlo (desclickeando oculto) y clickeando POP UP para poder verlo El POP UP deja de funcionar

**Comment by asergiop21** [comment]
Se cambio la función split por replace para eliminar caracteres especiales!

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461177-3804c080-769d-11ea-923e-64aea8c69d0e.png)
