### ISSUE TITLE
MAPA. No trae los popups luego de realizar una selección por polígono

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#332]
Captura de la selección:
![image](https://user-images.githubusercontent.com/36643035/77229345-2b944a00-6b6c-11ea-9a74-fbee5b657f77.png)

**Comment by asergiop21** [comment]
Se habilitó el popup al de termina de dibujar el polígono, antes se habilitaba cuando se desactivaba la función "dibujar poligono"

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461190-510d7180-769d-11ea-883c-fa45cc42f98f.png)
