### ISSUE TITLE
FILTRO. Cuando realizo un filtro los gráficos siguen mostrando el total de los datos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#334]
![image](https://user-images.githubusercontent.com/36643035/77236071-cc4d2e80-6b99-11ea-8379-4e25ff3ff574.png)

Si tenemos filtrados los puntos en el mapa sería necesario que los gráficos muestren los datos que correspondan a esos puntos.

**Comment by asergiop21** [comment]
Se corrigió función de filtrado en kpi

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461332-53bc9680-769e-11ea-8bdc-b3b3ac426711.png)
