### ISSUE TITLE
FILTRO. Mostrar en el select del modal los nombres de los atributos en vez del key

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#335]
Actualmente se muestra el `key`, esto no es lo óptimo ya que si el usuario modifica el `Nombre` del atributo, puede que no recuerde que datos contiene ese `key`.

Captura:
![image](https://user-images.githubusercontent.com/36643035/77238734-b8adc200-6bb1-11ea-95da-7ea8a9826994.png)

**Comment by asergiop21** [comment]
Se modifico en el select para que aparezca el nombre del campo y no el key
