### ISSUE TITLE
INTERFAZ. Permitir acceder a las acciones del proyecto desde otros módulos del mismo proyecto

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#341]
Ejemplo: No tener que pasar por el mapa para activar los campos visibles en indicadores

Captura actual:
![image](https://user-images.githubusercontent.com/36643035/77331780-f456a200-6cff-11ea-97c3-40d255aac47f.png)

**Comment by asergiop21** [comment]
Se agregaron los objectos para el funcionamiento el menu fuera del dashboard

**Comment by jvillegas88** [comment]
Falta:

- [ ] Ubicar las flechas de volver antes que el resto de los iconos

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78465349-f0952900-76ca-11ea-8609-b510870e5697.png)

![image](https://user-images.githubusercontent.com/36643035/78465358-060a5300-76cb-11ea-9ba3-595755bc4fab.png)

![image](https://user-images.githubusercontent.com/36643035/78465381-52559300-76cb-11ea-8e4e-767b170f4eb0.png)

![image](https://user-images.githubusercontent.com/36643035/78465391-6c8f7100-76cb-11ea-9ad3-70f04846f80a.png)

**Comment by jvillegas88** [comment]
### Horas de producción: 

@jvillegas88: 1:34
@asergiop21:
