### ISSUE TITLE
HEATMAP. La leyenda del mapa de calor no coincide con los datos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#352]
Captura:
![image](https://user-images.githubusercontent.com/36643035/77610477-942f4e00-6f01-11ea-9c8e-e0e21663517a.png)

**Comment by asergiop21** [comment]
Se realizó un array para obtener los valores mínimo y máximo

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78460875-04289b80-769b-11ea-806a-f3da8a0cf798.png)

Muestra valores `NaN`, probablemente sea por valores con decimales de tipo `string`.

Se vuelve a _Current Sprint_

**Comment by asergiop21** [comment]
se renombró la variable global con la variable que contiene el dato key
