### ISSUE TITLE
MAPA DE CALOR. El filtro debe mostrar el nombre del atributo y no el key

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#353]
Captura:
![image](https://user-images.githubusercontent.com/36643035/77610768-61398a00-6f02-11ea-8485-3e86eea2f8dc.png)

**Comment by asergiop21** [comment]
Se cambio en el nombre del filtro el atributo key por el nombre

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461222-80bc7980-769d-11ea-8491-630673809ec4.png)
