### ISSUE TITLE
MAPA DE CALOR. La herramienta no funciona cuando se selecciona un KPI

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#358]
Ejemplo: Se desea hacer un mapa de calor sobre el indicador `precio máximo por comuna`:

![image](https://user-images.githubusercontent.com/36643035/77615389-00b04a00-6f0e-11ea-81ec-2d1b45720061.png)

**Comment by asergiop21** [comment]
Se re factorizó la herramienta heatmap, agregando las funciones de filtros, igual a la de indicadores.

**Comment by jvillegas88** [comment]
Funcionando ok:
![image](https://user-images.githubusercontent.com/36643035/78460916-68e3f600-769b-11ea-93ec-7ec6a937d4ba.png)
