### ISSUE TITLE
MAPA. Evitar que las capas secundarias muestren los popups de la capa principal

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#361]
Ejemplo con capa principal `Propiedades / Fincas`, capa secundaria `Muestreos`. Cuando hago click sobre un muestreo me trae el popup de una propiedad pero como `undefined`:

![image](https://user-images.githubusercontent.com/36643035/78070622-7edb7900-7372-11ea-94cf-24e9af1ee13e.png)

**Comment by asergiop21** [comment]
Se habilitó solo el popup a la capa actual
