### ISSUE TITLE
INDICADORES. El análisis 'sum' no suma, cuenta los registros

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#363]
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/03e71bd0-ecfe-4fd3-a628-cb33e159ae50)
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/5094fb1c-a11e-415f-84f0-2aa10ac103c8)
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/5e4cdbf5-ea83-4d69-89f4-8c388883fc98)

**Comment by asergiop21** [comment]
se refactorizó las funciones de kpi por texto, ya que en algunos momentos se juntaban las funciones de contar y sumar.

![Captura de pantalla de 2020-03-28 11-26-19.png](https://images.zenhubusercontent.com/5b2a5abf2f27e82b33e6b336/50f9c119-a532-4a8c-81cc-9277c5c22989)

**Comment by jvillegas88** [comment]
Funcionando ok sum y count:
![image](https://user-images.githubusercontent.com/36643035/78461127-d80e1a00-769c-11ea-9cdf-8c7e3ae229a3.png)
