### ISSUE TITLE
INDICADOR TEXTO. Permitir utilizar los campos app_estado y app_usuario para calcular 'Seleccionado' y '% del Total'

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#366]
En la issue #304 se incluyeron los campos `app_estado` y `app_usuario` en el `json`. Ahora se deben hacer las modificaciones pertinentes para que se pueda calcular el `Seleccionado` y el `% del total` con los valores de esos campos.

**Comment by asergiop21** [comment]
Se agrego las relaciones de usuario y estado en los indicadores de texto

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461264-da24a880-769d-11ea-9d4d-e06879936f12.png)

![image](https://user-images.githubusercontent.com/36643035/78461271-e9a3f180-769d-11ea-96bc-15f742f8b243.png)
