### ISSUE TITLE
COLOREAR PUNTOS. El filtro debe mostrar el nombre del atributo y no el key

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#373]
![image](https://user-images.githubusercontent.com/36643035/77780833-5a5e6480-7033-11ea-9744-18cb47b23201.png)

**Comment by asergiop21** [comment]
Se cambio el atributo key por name en puntos coloreados

**Comment by jvillegas88** [comment]
Arreglado:
![image](https://user-images.githubusercontent.com/36643035/78460943-a47ec000-769b-11ea-9e6d-5de7f1724e66.png)
