### ISSUE TITLE
COLOREAR PUNTOS. Mostrar en el select del modal los nombres de los atributos en vez del key

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#375]
![image](https://user-images.githubusercontent.com/36643035/77781750-d9a06800-7034-11ea-9767-da289c81aa07.png)

**Comment by asergiop21** [comment]
Se cambio el atributo key por name en el modal

**Comment by jvillegas88** [comment]
Solucionado:
![image](https://user-images.githubusercontent.com/36643035/78460971-de4fc680-769b-11ea-9feb-1046c146c047.png)
