### ISSUE TITLE
MAPA DE CALOR. Mostrar en el select del modal los nombres de los atributos en vez del key

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#376]
![image](https://user-images.githubusercontent.com/36643035/77782062-6c410700-7035-11ea-8eec-59ae3ad73df3.png)

**Comment by asergiop21** [comment]
Se realizaron los cambio de key a nombre en el selector

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461236-a3e72900-769d-11ea-9bc5-7e25f480f5c9.png)
