### ISSUE TITLE
DIBUJAR POLÍGONO. Al realizar la selección no llegan datos a los gráficos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#380]
**Importante**: Esto solo sucede en `production` y `staging`, en `localhost` funciona correctamente

Plataforma:
![image](https://user-images.githubusercontent.com/36643035/77788751-90561580-7040-11ea-97b6-cdd10f58604b.png)

Consola JS:
![image](https://user-images.githubusercontent.com/36643035/77788862-c1364a80-7040-11ea-9264-9587cf306dd1.png)

**Comment by asergiop21** [comment]
Error de tipeo en nombre de variable

**Comment by jvillegas88** [comment]
![image](https://user-images.githubusercontent.com/36643035/78461292-10622800-769e-11ea-82d1-7f938efaf0dc.png)
