### ISSUE TITLE
Permitir importar listados

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#385]
Teniendo en cuenta que muchos listados se repiten en varias corporaciones sería útil poder importarlos en algún formato conocido, ejemplo `csv`

**Comment by LuchoAravena** [comment]
Se agregó la opción de importar listados, se validó que solo se puedan importar listados .csv, y se validó error si no se ha cargado ningún listado.csv

![Captura de pantalla de 2021-05-19 19-08-10](https://user-images.githubusercontent.com/19761457/118890851-c9e98000-b8d5-11eb-8d0d-de27bf3b04a2.png)
