### ISSUE TITLE
GRÁFICOS. Los datos que llegan a los gráficos son diferentes a los de la base de datos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#389]
Ejemplo:
![image](https://user-images.githubusercontent.com/36643035/77803104-2008bd80-705b-11ea-967d-21512c82b2b1.png)

**Comment by asergiop21** [comment]
Se eliminó la relación con los datos hijos. el joins estaba contando todo los datos de padres e hijos.
