### ISSUE TITLE
DATOS. Revisar datos en AMANDES. El grafico indica un valor aberrante que habria que sacarlo.

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#396]
Todos los datos de esta tabla fueron generados en forma Aleatoria por QGIS y luego exportada la tabla a GeoWorks-. No hay carga manual de datos, por lo que el error presente debe haberse generado en laboratorio. 
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/aa56e901-7639-4381-b352-131624776420)

**Comment by jvillegas88** [comment]
Aparentemente el proyecto `Nutrientes` se ha eliminado. No se pudo testear. 

![image](https://user-images.githubusercontent.com/36643035/78512505-7670ad00-777b-11ea-96ea-8598a7b6215a.png)
