### ISSUE TITLE
GRÁFICOS Nuevo titulo trae lista de Títulos de otros proyectos

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#397]
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/e957eb25-c115-41ab-94e5-cc094a9a5141)

**Comment by jvillegas88** [comment]
@jchambu Esto es por la función de autocompletado del navegador. No es algo propio de la aplicación. Favor de eliminar la issue.
