### ISSUE TITLE
GRÁFICOS. Quitar validación para mínimo y máximo del eje y

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#399]
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/3661bc8c-5e67-4cf5-af45-b4a6b52ebecc)

![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/98425121-d35c-49b9-8034-a5bb0efd649d)

**Comment by jvillegas88** [comment]
Esto sucede por dos validaciones:

`Mínimo`: está validado para que siempre comience en 0, se puede quitar la validación.
`Máximo`: está validado para que no se pueda seleccionar un valor menor al valor máximo de la muestra. Sino el gráfico no representaría fielmente a los datos.

Se discutirá en la reunión para tomar una decisión.

**Comment by jvillegas88** [comment]
Se tuvo que agregar una función para que los campos Mínimo y Máximo no fueran obligatorios. Ya que si estos no se completaban el gráfico se rompía.

Ticks custom:
![image](https://user-images.githubusercontent.com/36643035/78945428-a62ef600-7a96-11ea-94a8-f70adcee2aa3.png)

Gráfico resultante:
![image](https://user-images.githubusercontent.com/36643035/78945450-b1822180-7a96-11ea-80c2-533789eac1e2.png)

**Comment by jvillegas88** [comment]
Se tuvo que agregar una función para que los campos Mínimo y Máximo no fueran obligatorios. Ya que si estos no se completaban el gráfico se rompía.

Ticks custom:
![image](https://user-images.githubusercontent.com/36643035/78945517-dececf80-7a96-11ea-85d9-066a32a33025.png)

Gráfico resultante:
![image](https://user-images.githubusercontent.com/36643035/78945533-eaba9180-7a96-11ea-9b04-248441b2ca39.png)

**Comment by jvillegas88** [comment]
También disponible para horizontalBar:

Ticks custom:
![image](https://user-images.githubusercontent.com/36643035/78950330-cfef1980-7aa4-11ea-9f7e-737c364ac808.png)

Gráfico resultante:
![image](https://user-images.githubusercontent.com/36643035/78950368-f0b76f00-7aa4-11ea-8db7-3b21e1698c5a.png)

**Comment by jvillegas88** [comment]
### No se cobró por esta issue
