### ISSUE TITLE
ISCAMEN. Modificar los keys en la database para evitar superposición de datos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#401]

**Comment by flaviaarias** [comment]
Se cambiaron los nombres de las keys repetidas
![cambioskeys2.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/17636b50-5e2d-4376-9574-18b857bc1f29)

**Comment by jvillegas88** [comment]
### Horas de producción: 1
