### ISSUE TITLE
TODOAGRO. Eliminación de caracteres especiales en los keys

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#403]
Se eliminaron los acentos
![cambioskeys3.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/5473023d-21c6-4baf-9b20-a3fe374a612a)

![Captura de pantalla de 2020-04-02 12-20-03.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/658fd39b-6d47-41bc-87cd-9ac698da68cf)

**Comment by flaviaarias** [comment]
Se cambiaron 12 registros que contenían las keys con acentos

**Comment by jvillegas88** [comment]
### Horas de producción: 0,5
