### ISSUE TITLE
AVA. Eliminación de caracteres especiales en las key

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#404]
![cambioskeys4.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/adf2b992-f606-422e-9b99-568daf30d0f4)

![cambioskeys5.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/472de371-dd6a-4b7c-a1aa-acbb32425da8)

**Comment by flaviaarias** [comment]
Se revisaron los valores de los key dentro del Json. Solo una key que tiene espacio "Diametro tronco" tiene más de 14.000 valores. Se necesita cambiar a través de una función, ya que de forma manual sería imposible.
Queda pendiente aún ese cambio

**Comment by jvillegas88** [comment]
### Horas de producción: 0,5
