### ISSUE TITLE
ANDARIEGO. Eliminación de caracteres especiales en las keys

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#405]
![Captura de pantalla de 2020-04-02 11-03-57.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/8208d93f-062a-4dad-ba3f-b051a274cff4)

se verificó que no existan valores dentro del Json con esa key cambiada. No se encontró ninguno

**Comment by jvillegas88** [comment]
### Horas de producción: 0,5
