### ISSUE TITLE
DEMO. Eliminación de caracteres especiales en las keys

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#406]
Se elilminaron los caracteres especiales y se verificó que no existan esos valores dentro del JSON de propiedades. No se encontró ninguno

![Captura de pantalla de 2020-04-02 11-59-48.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/9e75d25c-02c6-452f-9451-7490f6d32d4c)

**Comment by jvillegas88** [comment]
### Horas de producción: 0,5
