### ISSUE TITLE
DIBUJAR POLÍGONO. Si dibujo un polígono sobre datos ya filtrados, cuando desactivo el filtro los gráficos no reaccionan a la nueva muestra

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#408]
Se testeo con el proyecto `Arriendos RM` de `staging`:

1. Se realizó un filtro por `Tipo = Casa`
2. Dibujo un polígono para trabajar con un porción más reducida de los datos
3. Quito el filtro `Tipo = Casa`
4. Los gráficos deberían reaccionar al total de puntos que contiene ahora pero sigue mostrando los que contenía cuando el filtro estaba aplicado.

Captura:
![image](https://user-images.githubusercontent.com/36643035/78461906-4b1a8f00-76a3-11ea-8f73-af19db7e7a4e.png)

**Comment by asergiop21** [comment]
Se cambiaron variables que contienen el tamaño del polígono dibujado
