### ISSUE TITLE
INDICADORES. Permitir utilizar campos de tipo listados simples y múltiples

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#416]
Ejemplo: Indicador Grafolita, dentro de Amandes/inspección. El indicador deseado es que me cuente la cantidad de inspecciones en los que se encontró grafolita 

___
Descripción actualizada por @jvillegas88:

Permitir análisis de acuerdo al siguiente esquema:

`Listados simples numéricos` permiten análisis `count`, `sum`, `avg`, `min`, `max`
`Listados simples texto` permiten análisis `count`
`Listados múltiples` (numéricos o texto) permiten análisis `count`

**Comment by jvillegas88** [comment]
Se modificó el título, descripción y se eliminó la etiqueta bug ya que el módulo indicadores sólo estaba desarrollado para trabajar con campos de tipo texto y numéricos. Permitir campos de tipo listado es un nuevo feature.

**Comment by asergiop21** [comment]
Se agrego en indicadores y filtros campos de selección multiple
