### ISSUE TITLE
USUARIOS. La edición del usuarios no muestra los valores de corporación ni rol almacenados 

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#418]
Captura:
![image](https://user-images.githubusercontent.com/36643035/78607120-dd05d180-7834-11ea-8f8f-9718fbd349ab.png)

**Comment by asergiop21** [comment]
Corregido!

![Captura de pantalla de 2020-04-09 09-46-23.png](https://images.zenhubusercontent.com/5b2a5abf2f27e82b33e6b336/e72236d5-5568-4d85-968b-aa9ab89cb06d)
