### ISSUE TITLE
DIBUJAR POLÍGONO. Al dibujar un polígono por segunda vez las funciones de indicadores y gráficos se ejecutan 2 veces

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#423]
Pasos pare reproducir el error:
1. Realizar una selección por polígono.
2. Eliminar la selección.
3. Realizar otra selección por polígono.
4. Error: 

Captura:
![image](https://user-images.githubusercontent.com/36643035/78834918-b034f400-79c5-11ea-935b-2b3da6ff77f7.png)

Log de objetos recibidos dos veces:
![image](https://user-images.githubusercontent.com/36643035/78834777-7663ed80-79c5-11ea-95c7-d4cbc43077aa.png)

**Comment by asergiop21** [comment]
Para poder solucionar esto se tuvo que agregar el toolbar de herramientas de dibujo de leaflet. 
[Uploading... Captura de pantalla de 2020-04-11 19-54-23.png ]
