### ISSUE TITLE
Modelador de Datos: No admite ubicacion de nuevo Campo en la estructura existente

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#434]
Corporacion Tomate2000, Proyecto Propiedades. Campos nuevos agregados: 
Calibracion Fue Aprobada?
Confiabilidad uso agroquimicos
Apto Cosecha Nocturna
Tipo de pulverizadora.

Todos estos campos fueron creados exitosamente, sin embargo, no permite ubicarlos en su lugar correspondiente dentro del modelo de datos.

**Comment by jvillegas88** [comment]
El problema es que habían nombres de campos repetidos cargados antes de que se agregaran las validaciones para evitar la carga de nombre de campos repetidos.
