### ISSUE TITLE
CORPORACION ISCAMEN. Doble barra de desplazamiento en Data Modeler

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#436]

**Comment by jvillegas88** [comment]
Favor aportar más información en la issue para poder detectar el problema. Sería útil una captura de pantalla y una descripción de que se estaba haciendo cuando ocurrió el error.

**Comment by jvillegas88** [comment]
Probablemente el problema reportado sea este:

![image](https://user-images.githubusercontent.com/36643035/82215341-a7e9a600-98ed-11ea-8acb-ed4b32363e3c.png)

La doble barra surge porque se muestra una notificación y altera el alto de la pantalla. Esto se debería solucionar el manejo de errores y notificaciones con [alerts ](https://getbootstrap.com/docs/4.0/components/alerts/) de Bootstrap.

**Comment by jvillegas88** [comment]
Se modificó el lugar donde aparece la notificación para evitar que se modifique el alto de la pantalla.

![image](https://user-images.githubusercontent.com/36643035/82449892-4f97dd00-9a82-11ea-8b4a-0831cf384767.png)
