### ISSUE TITLE
ISCAMEN. Lepidopteros. NO permite modificar Modelo de datos.

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#437]
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/01bc6dcb-8615-4c5d-b5df-533425fbbc3b)

Sucede al clickear el check box de Colorear Puntos en el campo Tipo de Trampa

**Comment by jvillegas88** [comment]
@JChambu lo corroboré pero funciona correctamente. Probablemente el error surgió porque estaba el server lleno, esto ya lo solucionó Ardengo.

Captura:
![image](https://user-images.githubusercontent.com/36643035/82214920-e9c61c80-98ec-11ea-8284-9023d4d9224a.png)
