### ISSUE TITLE
VALORES DE ID DUPLICADOS EN EL DATA MODELER

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#439]
Estoy con un tema QUE PUEDE SER MUY GRAVE, En el Data Modeler veo IDENTIFICADORES DE CAMPOS DUPLICADOS. Unos son de PADRES Y OTROS DE HIJOS pero el mismo numero se repite en el modelo. ESTO ES CORRECTO O ES UN BUG?
LO DIGO porque me esta generando duplicado cuando quiero mover un campo de lugar y no lo entiendo
Ejemplo Propiedades y fincas de Tomate.
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/0c10a145-fb59-4404-b8af-abf0d26743c5)

**Comment by jvillegas88** [comment]
@JChambu los datos de hijos y padres se guardan en tablas separadas por lo que no afecta que se repitan los IDs.
