### ISSUE TITLE
Cambiar el nombre de la cabecera de la columna actual para que levante el dato de roles que puede ver

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#505]
Rama: [feature/rol_edicion_campo](https://github.com/JChambu/geoworks/compare/feature/rol_edicion_campo)

**Comment by flaviaarias** [comment]
Se ajustó el ancho de la columna Visualizar y Editar para que sean fijas independientemente del valor que contengan para evitar que las columnas se muevan.

![Captura de pantalla de 2020-09-09 12-12-30.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/6d6942e4-534f-4cfb-a468-69bdd599d7cc)

**Comment by flaviaarias** [comment]
Se alinearon los campos al agregar un nuevo Atributo
Antes: ![Captura de pantalla de 2020-09-09 12-17-34.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/09d2bc82-fa49-45ef-a1ad-85530b904f95)

Después:
![Captura de pantalla de 2020-09-09 12-50-39.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/08f76044-0284-4d94-9041-20dffd250d81)
