### ISSUE TITLE
Dar formato a las alertas de error y éxito

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#512]

**Comment by flaviaarias** [comment]
Se elimina este tag que lo que hace es contar la cantidad de errores. Dejamos solo el detalle de los errores
<h2><%= pluralize(choice_list.errors.count, "error") %> prohibited this choice_list from being saved:</h2>

**Comment by flaviaarias** [comment]
Traducción de mensajes de success
![Captura de pantalla de 2020-08-31 23-33-26.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/30a0dbe3-80aa-40f1-bb09-db572c1e577d)
