### ISSUE TITLE
Agregar input y checkbox para leyenda en el formulario Gráficos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#519]
Rama: [feature/graphics_legends](https://github.com/JChambu/geoworks/tree/feature/graphics_legends)

Los parámetros a levantar son:

- `:legend_display` (checkbox)
- `:label_datasets` (input)

**Comment by flaviaarias** [comment]
Se agregaron los dos parámetros y se ajustó el estilo de los checkbox
Se testeo y funciona tanto el label como el check
![Captura de pantalla de 2020-08-31 22-53-45.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/87d9b28e-ba85-420e-9359-92a0a21c5a09)
![Captura de pantalla de 2020-08-31 22-54-45.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/d133db86-18de-4dbd-9960-741cb0be78e3)
