### ISSUE TITLE
Tomate2000. Reasignar y eliminar registros según descripción

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#547]
IMPORTANTE: 

- A todos los registros que se les realicen modificaciones se les debe actualizar `update_sequence` para que sea considerado como registro nuevo en la sincronización.
- Los registros padres se encuentran en la tabla `projects` y los registros hijos en la tabla `project_data_children`
- Los usuarios se encuentran en el schema `public`

Luis realizó varias consultas en el grupo GW-AT2000 y se decidieron realizar los siguientes cambios:

- [ ] Eliminar esta propiedad:

![image](https://user-images.githubusercontent.com/36643035/92184651-31cf6780-ee28-11ea-924c-4fc962f06f53.png)

- [ ] Eliminar este cuadro:

![image](https://user-images.githubusercontent.com/36643035/92183631-5bd35a80-ee25-11ea-9536-286b311c6f05.png)

- [ ] Pasar de `superadmin` (1) a `Diego Corominas` (69) esta propiedad:

![image](https://user-images.githubusercontent.com/36643035/92183830-e5832800-ee25-11ea-904c-7350ba08e49b.png)

- [ ] Pasar de `superadmin` (1) a `Agustina Flores` (181) esta propiedad:

![image](https://user-images.githubusercontent.com/36643035/92183870-fd5aac00-ee25-11ea-9511-7fcd50425b60.png)

- [ ] Pasar de `José Pierantonelli` (68) a `Agustina Flores` (181) esta propiedad:

![image](https://user-images.githubusercontent.com/36643035/92184154-cfc23280-ee26-11ea-8128-d9d5b3829394.png)

---

Concluido lo anterior se deben eliminar los registros padres (y sus respectivos hijos, si los tuviere) que se hayan creado con el user superadmin y que se encuentren cerca de las casas de Julián, Luis y Flavia. Adjunto coordenadas y ejemplos:

- [ ] Casa de Luis

https://www.google.com/maps?q=-33.00338493546458,-68.89591101747251

Ejemplos de inspecciones:
![image](https://user-images.githubusercontent.com/36643035/92183704-89b89f00-ee25-11ea-93e6-d3d40b6661f5.png)

- [ ] Casa de Julián

https://www.google.com/maps?q=-32.9020507,-68.8424952

Ejemplos de inspecciones:
![image](https://user-images.githubusercontent.com/36643035/92183675-7dccdd00-ee25-11ea-8498-ff7803a7d734.png)

- [ ] Casa Flavia:

https://www.google.com/maps?q=-32.97790037584412,-68.8507780373601

---

Por último los registros padres (y sus respectivos hijos, si los tuviere) que hayan sobrevivido, creados por el user superadmin se deberán pasar al usuario Diego Corominas (`id: 69`)

Cantidad de registros padres por proyecto:

- Inspecciones: 21
- Cuadros: 6
- Propiedades: 3

**Comment by FelixPad** [comment]
Siguiendo el orden de los puntos de la incidencia se procede a:

**-- ELIMINAR PROPIEDADES Y CUADROS (ROW_ACTIVE = FALSE)**
SELECT * FROM tomate2000.projects main 
--INNER JOIN public.users ON users.id = main.user_id
WHERE id = 211

UPDATE tomate2000.projects main SET row_active = 'false' WHERE id = 211

SELECT * FROM tomate2000.projects main 
--INNER JOIN tomate2000.project_data_children pd ON main.id = pd.project_id
WHERE main.id = 429

UPDATE tomate2000.projects main SET row_active = 'false' WHERE id = 429

**-- ACTUALIZAR USUARIOS**
SELECT * FROM tomate2000.projects main 
--INNER JOIN public.users ON users.id = main.user_id
WHERE main.id = 764
SELECT * FROM public.users WHERE id = 69

UPDATE tomate2000.projects SET user_id = 69, properties = jsonb_set(properties, '{app_usuario}', '"69"', true) 
WHERE id = 764


SELECT * FROM tomate2000.projects main 
--INNER JOIN public.users ON users.id = main.user_id
WHERE main.id = 756
SELECT * FROM public.users WHERE id = 181

UPDATE tomate2000.projects SET user_id = 181, properties = jsonb_set(properties, '{app_usuario}', '"181"', true) 
WHERE id = 756



SELECT * FROM tomate2000.projects main 
--INNER JOIN public.users ON users.id = main.user_id
WHERE main.id = 1949
SELECT * FROM public.users WHERE id = 181

UPDATE tomate2000.projects SET user_id = 181, properties = jsonb_set(properties, '{app_usuario}', '"181"', true) 
WHERE id = 1949


-- ACTUALIZAR HIJOS
SELECT * FROM tomate2000.project_data_children pd
WHERE pd.project_id = 764

UPDATE tomate2000.project_data_children SET user_id = 69 
WHERE id = 524


SELECT * FROM tomate2000.project_data_children pd 
--INNER JOIN public.users ON users.id = main.user_id
WHERE pd.project_id = 756

UPDATE tomate2000.project_data_children SET user_id = 181
WHERE project_id = 756

**BÚSQUEDA,  ELIMINACIÓN Y ACTUALIZACIÓN DE REGISTROS POR USUARIO SUPERADMIN**

-- Parents
SELECT
users.name,
main.id,
main.properties,
main.project_type_id,
main.the_geom,
main.row_active,
main.created_at
FROM tomate2000.projects main 
INNER JOIN public.users ON users.id = main.user_id
WHERE user_id = 1 
AND main.id IN (213,177,176,878,227,214,841,842,163,175,
				   173,228,839,843,838,1014,1015,1016,
				   178,179,181,182,207,208,209,210,219,221)
				   ORDER BY main.row_active ASC;


DELETE FROM tomate2000.projects WHERE id IN (213,177,176,878,227,214,841,842,163,175,
				   173,228,839,843,838,1014,1015,1016,
				   178,179,181,182,207,208,209,210,219,221);

-- Children
SELECT * FROM tomate2000.project_data_children WHERE project_id IN (213,177,176,878,227,214,841,842,163,175,
				   173,228,839,843,838,1014,1015,1016,
				   178,179,181,182,207,208,209,210,219,221);
				   
DELETE FROM tomate2000.project_data_children WHERE project_id IN (213,177,176,878,227,214,841,842,163,175,
				   173,228,839,843,838,1014,1015,1016,
				   178,179,181,182,207,208,209,210);
				   
**--UPDATE SUPERADMIN A COROMINAS**
SELECT
users.name,
main.id,
main.properties,
main.project_type_id,
main.the_geom,
main.row_active,
main.created_at,
main.update_sequence
FROM tomate2000.projects main 
INNER JOIN public.users ON users.id = main.user_id
WHERE user_id = 69 ORDER BY row_active DESC

UPDATE tomate2000.projects SET user_id = 69 WHERE user_id = 1
