### ISSUE TITLE
Tomate2000. Pasar a temporada anterior las recomendaciones anteriores al 30/06/20 (inclusive)

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#549]
Se debe pasar a `false` la columna `current_season`. Las recomendaciones son hijos en el proyecto "Cuadros / Recomendaciones" (`project_type_id=3`) por lo que se encuentran en la tabla `project_data_children`. La fecha a tener en cuenta es el valor de la columna `created_at`.

Ejemplo:
30/06/20 current_season: false
01/07/20 curren_season: true

IMPORTANTE: A todos los registros que se les realicen modificaciones se les debe actualizar update_sequence para que sea considerado como registro nuevo en la sincronización

---

Luis dijo:
> Es el mismo caso con las recomendaciones, que si bien no se muestran en el mapa, si en la analítica y todas las recomendaciones desde el 1/7 pra atrás, ya no sirven, es estadistica con time slider. Las recomendaciones del 1// para adelante ya son de esta temporada y deben estar en las gráficas reflejadas.

**Comment by FelixPad** [comment]
Al igual que en para projects  (datos padre), se genera un Trigger Function y un Trigger para actualizar automaticamente el campo update_sequence y la secuencia propiamente dicha

CREATE FUNCTION tomate2000.update_sequence_children()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
BEGIN
  NEW.update_sequence := nextval('tomate2000.project_data_children_update_sequence_seq');
  RETURN NEW;
END; 
$BODY$;

CREATE TRIGGER trg_children_update_sequence
    BEFORE UPDATE 
    ON tomate2000.project_data_children
    FOR EACH ROW
    EXECUTE PROCEDURE tomate2000.update_sequence_children();

**Se hace una corroboración de los datos de recomendaciones y se procede al update**

SELECT
users.name AS name,
pd.id,
pd.properties,
pd.created_at,
pd.current_season,
main.project_type_id,
pd.row_active
FROM tomate2000.project_data_children pd
INNER JOIN tomate2000.projects main ON main.id = pd.project_id
INNER JOIN public.users ON users.id = main.user_id
INNER JOIN tomate2000.project_statuses ON project_statuses.id = main.project_status_id
WHERE pd.id IN (301,323,275,312,283,293,302,375,376,370,371,324,276,284,313,303,365,325,294,277,285,336,337,314,333,334,326,295,278,304,315,286,296,332,365,327,279,316,742,747,748,751,752,297,280,328,288,338,306,317,743,745,749,750,754,755,756,757,758,761,762,763,740)
AND pd.created_at < '2020-07-01' /*AND users.id != 1  AND users.role = '2' AND main.row_active = 'true'*/
ORDER BY pd.created_at

**--UPDATE**
UPDATE tomate2000.project_data_children SET current_season = 'false'
WHERE id IN (301,323,275,312,283,293,302,375,376,370,371,324,276,284,313,303,365,325,294,277,285,336,337,314,333,334,326,295,278,304,315,286,296,332,365,327,279,316,742,747,748,751,752,297,280,328,288,338,306,317,743,745,749,750,754,755,756,757,758,761,762,763,740)
AND created_at < '2020-07-01'

**Comment by jvillegas88** [comment]
Teniendo en cuenta que se estaba interpretando erróneamente cuando considerar a un registro como recomendación, habían quedado 32 registros sin pasar a la temporada anterior. Se corrigió este problema:

```
SELECT *
FROM tomate2000.project_data_children pd
WHERE pd.project_field_id IN (416, 423, 404, 405, 406, 403, 410, 411, 414)
AND pd.gwm_created_at::date < '2020-07-01'
AND pd.current_season = 'true'
```

```
UPDATE tomate2000.project_data_children pd SET current_season = false
WHERE pd.project_field_id IN (416, 423, 404, 405, 406, 403, 410, 411, 414)
AND pd.gwm_created_at::date < '2020-07-01'
AND pd.current_season = 'true'
```
