### ISSUE TITLE
Remover "Departamento de " de todos departamentos de registros padres

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#556]
Se ha modificado la forma en que se genera automáticamente el departamento en GWMobile, por lo que ahora el dato va a llegar solamente con el nombre del departamento. Se de sea eliminar la cadena "Departamento de " de cada registro ya almacenado. (No olvidar el espacio luego de "de_")

Las corporaciones (schemas en la db) a los que hay que aplicarles este cambio son:

- tomate2000
- amandes
- iscamen
- agq

_Ejemplos_:

Antes:
```
"departamento": "Departamento de San Carlos",
```

Ahora: 
```
"departamento": "San Carlos",
```

Este dato se encuentra en la tabla `projects`, en la columna `properties`, con el key `departamento`

**Comment by FelixPad** [comment]
**ACTUALIZACIÓN DE CAMPO PROPERTIES, KEY 'DEPARTAMENTO', ELIMINANDO 'DEPARTAMENTO DE'**

SELECT properties -> 'departamento' FROM tomate2000.projects WHERE properties ->> 'departamento' ILIKE '%departamento de%'

--select trim
SELECT properties -> 'departamento', trim(leading 'Departamento de ' from properties ->> 'departamento') FROM tomate2000.projects 
	WHERE properties ->> 'departamento' ILIKE '%departamento de%';
	
SELECT properties -> 'departamento', trim(leading 'Departamento de ' from properties ->> 'departamento') FROM amandes.projects 
WHERE properties ->> 'departamento' ILIKE '%departamento de%';
-- amandes no tiene datos de departamento

SELECT properties -> 'departamento', trim(leading 'Departamento de ' from properties ->> 'departamento') FROM iscamen.projects 
	WHERE properties ->> 'departamento' ILIKE '%departamento de%';

SELECT properties -> 'departamento', trim(leading 'Departamento de ' from properties ->> 'departamento') FROM agq.projects 
	WHERE properties ->> 'departamento' ILIKE '%departamento de%';
--select replace
select id, properties -> 'departamento', replace(properties::text, 'Departamento de ', '')::jsonb
from tomate2000.projects WHERE properties ->> 'departamento' ILIKE '%departamento de%';

--update replace
UPDATE tomate2000.projects SET properties = replace(properties::text, 'Departamento de ', '')::jsonb
WHERE properties ->> 'departamento' ILIKE '%departamento de%';

UPDATE iscamen.projects SET properties = replace(properties::text, 'Departamento de ', '')::jsonb
WHERE properties ->> 'departamento' ILIKE '%departamento de%';

UPDATE agq.projects SET properties = replace(properties::text, 'Departamento de ', '')::jsonb
WHERE properties ->> 'departamento' ILIKE '%departamento de%';
