### ISSUE TITLE
NO SE PUEDE SETEAR EDICION MULTIPLE EN COPORACION TOMATE, PROYECTO Cuadro productivo 

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#559]
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/1f0e9073-6823-446d-b656-92bd4181ad42)

**Comment by jvillegas88** [comment]
El problema es que habían nombres de campos repetidos cargados antes de que se agregaran las validaciones para evitar la carga de nombre de campos repetidos. Se agregaron espacios a los nombres de campos para mantener el mismo nombre pero que la cadena de caracteres fuera diferente.
