### ISSUE TITLE
LEYENDA EN GRAFICOS 

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#561]
![image.png](https://images.zenhubusercontent.com/5d72a97ff644fe77911a577e/acc1d696-8ec2-4597-9e1b-8383e434361

Favor modificar el color de la leyenda, al tener fondo gris la letra no se distingue. Probar con blanco

**Comment by jvillegas88** [comment]
Ya se corrigió, se cierra la issue 

Captura:
![image](https://user-images.githubusercontent.com/36643035/93655443-bf4eb200-f9f9-11ea-9fc8-dd0ca6b98a56.png)
