### ISSUE TITLE
Completar los campos gwm_created_at y gwm_updated_at con los valores de created_at y updated_at

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#562]
Los nuevos campos van a almacenar las fechas de creación y actualización de los registros en GWMobile (`gwm_created_at` y `gwm_updated_at` respectivamente). Los registros ya almacenado se van a completar con los valores de `created_at` y `updated_at` que existen en la base actualmente (los cuales se generaron con la sincronización del registro)

Completar las tablas `projects` y `project_data_children` de los schemas `agq`, `tomate2000` e `iscamen`

**Comment by FelixPad** [comment]
**Se realizan consultas para analizar los datos de los campos gwm_created_at y gwm_updated_at de cada una de las tablas de los esquemas a actualizar, una vez comprobados los datos se procede con el Update**

SELECT * FROM tomate2000.projects WHERE gwm_created_at IS NOT NULL

SELECT * FROM tomate2000.projects WHERE gwm_updated_at IS NOT NULL

SELECT id, created_at, gwm_created_at, updated_at, gwm_updated_at FROM tomate2000.projects 
WHERE gwm_created_at IS NOT NULL
ORDER BY id ASC

SELECT id, created_at, gwm_created_at, updated_at, gwm_updated_at FROM tomate2000.project_data_children
WHERE gwm_created_at IS NOT NULL
ORDER BY id ASC

SELECT id, created_at, gwm_created_at, updated_at, gwm_updated_at FROM agq.projects 
WHERE gwm_created_at IS NOT NULL
ORDER BY id ASC

SELECT id, created_at, gwm_created_at, updated_at, gwm_updated_at FROM agq.project_data_children
WHERE gwm_created_at IS NOT NULL
ORDER BY id ASC

SELECT id, created_at, gwm_created_at, updated_at, gwm_updated_at FROM iscamen.projects 
WHERE gwm_updated_at IS NOT NULL
ORDER BY id ASC

SELECT id, created_at, gwm_created_at, updated_at, gwm_updated_at FROM iscamen.project_data_children
WHERE gwm_created_at IS NOT NULL
ORDER BY id ASC

--UPDATES
--tomate
UPDATE tomate2000.projects SET gwm_created_at = created_at, gwm_updated_at = updated_at

UPDATE tomate2000.project_data_children SET gwm_created_at = created_at, gwm_updated_at = updated_at

--agq
UPDATE agq.projects SET gwm_created_at = created_at, gwm_updated_at = updated_at

UPDATE agq.project_data_children SET gwm_created_at = created_at, gwm_updated_at = updated_at

--iscamen
UPDATE iscamen.projects SET gwm_created_at = created_at, gwm_updated_at = updated_at

UPDATE iscamen.project_data_children SET gwm_created_at = created_at, gwm_updated_at = updated_at
