### ISSUE TITLE
Modificar el formato de los datos almacenados con tipo de campo "Listado de opción única" para que concuerden con el nuevo formato

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#563]
Al generar un proyecto en Geoworks, a cada campo que agregamos al prototipo le podemos asignar un tipo de campo de acuerdo al dato que va a almacenar. Estos tipos de campos se encuentran almacenados en la tabla `field_types` del `schema` `public`:

![image](https://user-images.githubusercontent.com/36643035/92335961-469f3b80-f072-11ea-93b2-11d9684c301b.png)

Esta tabla se relaciona con las tablas `project_fields` y `project_subfields` que contienen todos los campos padres e hijos respectivamente de todos los proyectos de la corporación. Ejemplo en amandes:

![image](https://user-images.githubusercontent.com/36643035/92336412-98e25b80-f076-11ea-91fb-487718da4dd3.png)

Cada uno de los campos de la tabla anterior tiene un `key` almacenado en su columna, el cual es utilizado en la tabla `projects` dentro de la columna `properties` para identificar el valor del registro padre. Por otro lado, los registros hijos, almacenados en la tabla `project_data_children`, utilizan el `id` correspondiente a los campos de la tabla `project_subfields` para identificar el valor del registro almacenado en la columna `properties`.

Lo se necesita es modificar el formato de los datos de padres e hijos alojados dentro de la columna properties de las que tengan tipo de campo Listado de opción única para que concuerden con el formato actual.

Así se almacenaban:
```
{
    "difusion_malezas": "Esporádica"
}
```

Así se van a almacenar a partir de hoy:

```
{
    "difusion_malezas": [
        "Esporádica"
    ]
}
```

Lo que se busca es corregir todos los registros de `projects` y `project_data_children` ya almacenados para que den con el formato que van a llegar los registros ahora. Y, de este modo, evitar este tipo de problemas:

![image](https://user-images.githubusercontent.com/36643035/92336331-cda1e300-f075-11ea-90f6-67ed91d6e801.png)

**Comment by FelixPad** [comment]
**Se realiza el update en la tabla projects de los valores de las key relacionadas con field_type_id = 2 en los esquemas de tomate2000, agq, amandes e iscamen **
*Nota: esto tomo un buen tiempo ya que cada update hubo que realizarlo de forma manual para cada uno de los keys identificados.

--UPDATE 
update iscamen.projects
set properties = jsonb_set(
        properties, 
        array['trampa_tipo'], 
        to_jsonb(string_to_array(replace((properties->'trampa_tipo')::text, '"',''), ';'))
        )
		WHERE jsonb_typeof(properties->'trampa_tipo') = 'string'
returning properties, update_sequence;
