### ISSUE TITLE
Tomate2000. Completar los valores de app_estado con los de la columna project_status_id

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#564]
Luego de modificar algunos estados desde la columna `project_status_id`, es necesario aplicar los cambios al estado que se encuentra dentro del json. Todos los registros se encuentran en la tabla `projects`

Hay 606 registros con diferencias:
```
SELECT "id", 
(properties ->> 'app_estado')::bigint as estado_json, 
project_status_id as estado_columna
FROM tomate2000.projects
WHERE (properties ->> 'app_estado')::bigint != project_status_id
```

Captura:
![image](https://user-images.githubusercontent.com/36643035/95787848-b1b2e200-0cb0-11eb-8490-c8459f78aaf6.png)

**Comment by FelixPad** [comment]
**Se comparan los valores de los estados de los dos campos (properties, project_status_id), se actualiza el campo properties, key "app_estado" con los valores corregidos de project_status_id y se verifican los cambios**

SELECT
properties -> 'app_estado',
project_status_id
FROM tomate2000.projects
ORDER BY project_status_id ASC;

--UPDATE
UPDATE tomate2000.projects AS p 
SET properties = (
  SELECT row_to_json(t) FROM (
    SELECT project_status_id as app_estado FROM tomate2000.projects AS p2 WHERE p.id = p2.id
  ) t
)::jsonb;
