### ISSUE TITLE
Detectar y corregir errores de topología en tomate2000

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#585]
Actualmente hay varios polígonos que no están bien dibujados y esto impide que la herramienta de heredar estados funcione correctamente. Se busca detectar estas imperfecciones y corregirlas.

Datos útiles:

- Las geometrías están almacenadas en la columna the_geom de la tabla projects.
- Propiedades / Fincas (`project_type_id = 5`) contiene a Cuadros / Recomendaciones (`project_type_id = 3`)

Ejemplo:

![image](https://user-images.githubusercontent.com/36643035/93824674-36728900-fc3a-11ea-9cbd-7b838ad0b2e1.png)

**Comment by FelixPad** [comment]
**QUERIES GENERADAS PARA CONSULTAS Y ACTUALIZACIONES DE GEOMETRIAS**

SELECT a.id, a.the_geom, ST_AsText(ST_Intersection(a.the_geom, b.the_geom)) as intersect_ab FROM tomate2000.projects a, tomate2000.projects b 
WHERE ST_Overlaps(a.the_geom, b.the_geom) AND ST_isvalid(a.the_geom)='t' AND ST_isvalid(b.the_geom)='t'
AND b.project_type_id = 5 AND b.row_active = true AND a.project_type_id = 5 AND a.row_active = true
GROUP BY a.id, b.the_geom;

SELECT a.the_geom, ST_INTERSECTION(a.the_geom, b.the_geom), b.the_geom
FROM tomate2000.projects a, tomate2000.projects b
WHERE a.id < b.id 
AND ST_INTERSECTS(a.the_geom, b.the_geom) AND ST_isvalid(a.the_geom)='t' AND ST_isvalid(b.the_geom)='t'
AND a.project_type_id = 5 AND a.row_active = true AND b.project_type_id = 5 AND b.row_active = true;

-- vista
CREATE MATERIALIZED VIEW tomate2000.projects_intersects_cuadros AS
SELECT a.the_geom, ST_INTERSECTION(a.the_geom, b.the_geom) --, b.the_geom
FROM tomate2000.projects a, tomate2000.projects b
WHERE a.id < b.id 
AND ST_INTERSECTS(a.the_geom, b.the_geom) AND ST_isvalid(a.the_geom)='t' AND ST_isvalid(b.the_geom)='t'
AND a.project_type_id = 3 AND a.row_active = true AND b.project_type_id = 3 AND b.row_active = true
WITH DATA;

CREATE MATERIALIZED VIEW tomate2000.projects_intersects_cuadros_b AS
SELECT b.the_geom, ST_INTERSECTION(a.the_geom, b.the_geom) --, b.the_geom
FROM tomate2000.projects a, tomate2000.projects b
WHERE a.id < b.id 
AND ST_INTERSECTS(a.the_geom, b.the_geom) AND ST_isvalid(a.the_geom)='t' AND ST_isvalid(b.the_geom)='t'
AND a.project_type_id = 3 AND a.row_active = true AND b.project_type_id = 3 AND b.row_active = true
WITH DATA;

--IDs
select id, properties ->> 'departamento' as departamento, 
properties ->> 'provincia' as provincia, properties ->> 'propietario_razon_social' as razon_social, 
gwm_created_at, the_geom from tomate2000.projects where id in (2383,2469,676,2930,628)

--cuadros
select id, properties ->> 'localidad' as localidad, properties ->> 'departamento' as departamento, 
properties ->> 'provincia' as provincia, properties ->> 'industria' as razon_social, 
gwm_created_at from tomate2000.projects where id in (
3966,3965,1731,1742,3046,3045,1745,1934,3044,3042,1929,5712,3696,5171,1134,406,1045,6046,1046,6045,1047,6044,761,2128,671,456,913,2926,883,1953
,6762,885,888,6310,2736,669,4756,1313,620,448,4460,382,692,2259,1800,1805,363,1662,
3488,3017)

--data
892,893 mismos datos

select properties, row_active, row_enabled from tomate2000.projects where id in (892,893)
update tomate2000.projects set row_enabled = false where id = 892

-- 25/01/2021
-- PROPIEDADES
SELECT id, ST_Difference(the_geom, (SELECT ST_Union(b.the_geom) 
                                FROM tomate2000.projects b
                                WHERE ST_Intersects(a.the_geom, b.the_geom)
                                  AND a.id != b.id AND ST_isvalid(a.the_geom)='t' AND ST_isvalid(b.the_geom)='t' AND a.id IN(2373,2361 ))
FROM tomate2000.projects a;

SELECT properties FROM tomate2000.projects WHERE id IN (1897,1963) AND row_active = true
SELECT properties FROM tomate2000.projects WHERE id IN (1730,3963) AND row_active = true
SELECT properties FROM tomate2000.projects WHERE id IN (1628,3062) AND row_active = true
SELECT properties FROM tomate2000.projects WHERE id IN (774,834,3943) AND row_active = true
SELECT properties FROM tomate2000.projects WHERE id IN (628,2930) AND row_active = true
SELECT properties, gwm_created_at FROM tomate2000.projects WHERE id IN (2079,2064) AND row_active = true

--NUEVAS CONSULTAS 07/02/2021
SELECT properties, gwm_created_at FROM tomate2000.projects WHERE id IN (672,326) AND row_active = true
SELECT properties, gwm_created_at FROM tomate2000.projects WHERE id IN (2370,599) AND row_active = true

UPDATE tomate2000.projects SET row_active = 'false' WHERE id IN (1744,1737,1897,1730,1628,774,834,628)

UPDATE tomate2000.projects SET row_active = 'false' WHERE id = 2064


--CUADROS

SELECT properties FROM tomate2000.projects WHERE id IN (3045,1745) AND row_active = true;

SELECT properties FROM tomate2000.projects WHERE id IN (3046,1742) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (3965,3966,1731) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (3696,5171) AND row_active = true --no, consultar

SELECT properties FROM tomate2000.projects WHERE id IN (1929,3042,5712) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (1134,406) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (1047,6044) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (1046,6045) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (1045,6046) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (761,2128) AND row_active = trueç

SELECT properties FROM tomate2000.projects WHERE id IN (671,456) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (913,2926) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (883,1953) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (6762,885) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (888,6310) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (2736,669) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (620,448) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (4460,7361,382) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (692,2259) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (892,893) AND row_active = true

SELECT properties FROM tomate2000.projects WHERE id IN (363,1662) AND row_active = true


UPDATE tomate2000.projects SET row_active = 'false' WHERE id IN (1742,1745,1731,1929,1134,1047,6045,1045,2128,671,913,883,885,888,2736,620,382,2259,892,363)

-- PRUEBA
						 
SELECT p.id, n.properties
 , CASE 
   WHEN ST_CoveredBy(p.the_geom, n.the_geom) 
   THEN p.the_geom 
   ELSE 
    ST_Multi(
      ST_Intersection(p.the_geom,n.the_geom)
      ) END AS geom 
 FROM tomate2000.projects AS p 
   INNER JOIN tomate2000.projects AS n 
    ON ST_Intersects(p.the_geom, n.the_geom)
	WHERE ST_isvalid(p.the_geom)='t' AND ST_isvalid(n.the_geom)='t'
	AND p.project_type_id = 5 AND p.row_active = true AND n.project_type_id = 5 AND n.row_active = true;

SELECT p.id, n.properties
 ,  
    ST_Multi(
      ST_Intersection(p.the_geom,n.the_geom)
      ) AS geom 
 FROM tomate2000.projects AS p 
   INNER JOIN tomate2000.projects AS n 
    ON ST_Intersects(p.the_geom, n.the_geom)
	WHERE 
	p.project_type_id = 5 AND p.row_active = true AND n.project_type_id = 5 AND n.row_active = true
	AND ST_isvalid(p.the_geom)='t' AND ST_isvalid(n.the_geom)='t'
	;
27/01/2021

-- IDs que se volvierona a poner en row_active = true
						 
UPDATE tomate2000.projects SET row_active = 'true' WHERE id IN (1742,1745,1731,1929,1134,1047,6045,
																 1045,2128,671,913,883,885,888,
																 2736,620,382,2259,892,363)
						 
16/02/2021
--CUADROS
select * from tomate2000.projects where id in (3696,5171)
select * from tomate2000.projects where id in (1134,406)
select * from tomate2000.projects where id in (6046,1045)
select * from tomate2000.projects where id in (1046,6045)
select * from tomate2000.projects where id in (1047,6044)
select * from tomate2000.projects where id in (363,1662)
select * from tomate2000.projects where id in (885,6762)
select * from tomate2000.projects where id in (888,6310)
select * from tomate2000.projects where id in (1178,7954)
select * from tomate2000.projects where id in (1179,7757)
select * from tomate2000.projects where id in (448,620)

update tomate2000.projects set row_active = false where id = 1134

update tomate2000.projects set row_active = false where id in (1047,1046,1045)

update tomate2000.projects set row_active = false where id in (885)

update tomate2000.projects set row_active = false where id in (888)

update tomate2000.projects set row_active = false where id in (7954)

update tomate2000.projects set row_active = false where id in (7757)

update tomate2000.projects set row_active = false where id in (620)

**Comment by FelixPad** [comment]
**CREACION DE VISTAS MATERIALIZADAS PARA COMPARAR ERRORES TOPOLOGICOS**

**--PROPIEDADES**

CREATE MATERIALIZED VIEW tomate2000.projects_overlaps
TABLESPACE pg_default
AS
 SELECT a.id,
    a.the_geom
   FROM tomate2000.projects a,
    tomate2000.projects b
  WHERE a.id < b.id AND st_overlaps(a.the_geom, b.the_geom) AND a.project_type_id = 5 AND b.project_type_id = 5 AND st_isvalid(a.the_geom) = true AND st_isvalid(b.the_geom) = true AND a.row_active = true AND b.row_active = true
WITH DATA;

CREATE MATERIALIZED VIEW tomate2000.projects_overlaps_b
TABLESPACE pg_default
AS
 SELECT b.id,
    b.the_geom
   FROM tomate2000.projects a,
    tomate2000.projects b
  WHERE a.id < b.id AND st_overlaps(a.the_geom, b.the_geom) AND a.project_type_id = 5 AND b.project_type_id = 5 AND st_isvalid(a.the_geom) = true AND st_isvalid(b.the_geom) = true AND a.row_active = true AND b.row_active = true
WITH DATA;

**--CUADROS**

CREATE MATERIALIZED VIEW tomate2000.projects_overlaps_cuadros
TABLESPACE pg_default
AS
 SELECT a.id,
    a.the_geom
   FROM tomate2000.projects a,
    tomate2000.projects b
  WHERE a.id < b.id AND st_overlaps(a.the_geom, b.the_geom) AND a.project_type_id = 3 AND b.project_type_id = 3 AND st_isvalid(a.the_geom) = true AND st_isvalid(b.the_geom) = true AND a.row_active = true AND b.row_active = true
WITH DATA;

CREATE MATERIALIZED VIEW tomate2000.projects_overlaps_cuadros_b
TABLESPACE pg_default
AS
 SELECT b.id,
    b.the_geom
   FROM tomate2000.projects a,
    tomate2000.projects b
  WHERE a.id < b.id AND st_overlaps(a.the_geom, b.the_geom) AND a.project_type_id = 3 AND b.project_type_id = 3 AND st_isvalid(a.the_geom) = true AND st_isvalid(b.the_geom) = true AND a.row_active = true AND b.row_active = true
WITH DATA;
