### ISSUE TITLE
El formulario de Editar Estado debe mostrar los valores almacenados

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#589]
Ejemplo:

![image.png](https://images.zenhubusercontent.com/5b29d0e0f378ea1890b3db84/850b723c-ebce-4d45-888a-106fa4c33e17)

En este caso, el tipo de estado debería mostrar Heredable y a su vez mostrar las opciones de proyecto y estado que hereda. Tomar como ejemplo el selector anidado del formulario usuarios (admin).

**Comment by flaviaarias** [comment]
Se cargan las opciones seleccionadas para el caso de Heredable: Tiempo, proyecto del que hereda y Estado desde el que hereda
Además cuando se cambia de estado a Default o Asignable, se limpian las variables correspondientes al tipo de estado heredable
