### ISSUE TITLE
Unificar los valores del eje x en gráficos con más de una serie

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#619]
![bug_ejex.jpg](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/8b1d92b2-74f3-44f4-9461-9af922c9abec)

**Comment by flaviaarias** [comment]
Cuando se deployó la rama se encontró que los gráficos de usuarios se rompen.
El tema es el orden alfabético 
El query que trae los usuarios ordena 1) Agustina 2) Agustín.

0: "Abel Espinoza"
    1. 1: "Agustina Flores"
    2. 2: "Agustín Recabarren"
    3. 3: "Alberto Herrera"
    4. 4: "Analía Diaz"
    5. 5: "Diego Corominas"
    6. 6: "Elio Cantoni"
    7. 7: "Javier Arenas"
    8. 8: "José Pierantonelli"
    9. 9: "Juan Ávila"
    10. 10: "Mercedes"
    11. 11: "Pablo Guevara"

Se probó un query en local y los ordena bien como se muestra a continaución

![Captura de pantalla de 2020-10-13 00-54-40.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/87609bb7-4c79-402e-a58a-68aa59a758e7)

Sugiero revisar la causa por la que sql está trayendo desordenado Agustina y Agustín antes de solucionarlo desde el front.

**Comment by jvillegas88** [comment]
Hice unas pruebas y el orden con el que los ordena `SQL` es el mismo con el que los ordena la función `sort` de js. 

`ORDER BY`:

![image](https://user-images.githubusercontent.com/36643035/95895224-b6cf6a00-0d60-11eb-9996-b30e76314320.png)

`sort()`:

![image](https://user-images.githubusercontent.com/36643035/95895592-48d77280-0d61-11eb-9aec-6d50121ac5e1.png)

Quizás el error esté al comparar los registros de los dos arrays

**Comment by flaviaarias** [comment]
El tema es que la función sort coloca la ñ al final

![Captura de pantalla de 2020-10-13 17-53-26.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/c593f467-ee68-4f26-b4f2-2121ba4623ac)

**Comment by flaviaarias** [comment]
Para el manejo de los nulls se hizo lo siguiente
Los arrays se ordenan primero con sort() que coloca los nulls al final
En la función sort.localeCompare se saltea los nulls para evitar que se rompa la función
Finalmente se cambia la palabra null por "sin datos"
Este sería el resultado

![Captura de pantalla de 2020-10-14 14-40-08.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/cfe2363a-b7ca-4e04-a84a-f42d09255fe7)

**Comment by jvillegas88** [comment]
Los valores de Agustina y Agustín están intercambiados:

KPI recomendaciones por extensionsita:
![image](https://user-images.githubusercontent.com/36643035/96055157-ba92e780-0e59-11eb-98c9-c6771cb00cbc.png)

![image](https://user-images.githubusercontent.com/36643035/96055164-c088c880-0e59-11eb-8e86-3bbeb0dac69f.png)

**Comment by jvillegas88** [comment]
@flaviaarias dijo: 

> Le cloné los arrays temporales porque al tener un = eran el mismo objeto. Ahora debería funcionar. En local me trae Agustina 84 y Agustín 45

**Comment by jvillegas88** [comment]
Se testearon los datos y todos coinciden con las indicadores desde la db:

![image](https://user-images.githubusercontent.com/36643035/96059888-6e4da480-0e65-11eb-9ac3-a446b13865fd.png)

Visitas:
![image](https://user-images.githubusercontent.com/36643035/96059903-760d4900-0e65-11eb-9556-b8cd178e2d07.png)

Recomendaciones:
![image](https://user-images.githubusercontent.com/36643035/96059964-950bdb00-0e65-11eb-86aa-9398c7b9629b.png)

Inspecciones:
![image](https://user-images.githubusercontent.com/36643035/96059988-ae148c00-0e65-11eb-954d-4f94590063f6.png)
