### ISSUE TITLE
Agregar select para la carga de enable_period en el formulario de Proyectos

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#654]
El `select` debe agregarse en en la carga/edición de un proyecto (tanto por archivos como por atributos).

Las opciones que debe contener el selecto son:

- `Nunca`
- `Semana`
- `Mes`
- `Año`

Siendo `Nunca` la primera opción, ésta sera la que se cargue de manera predeterminada sino se modifica el parámetro

El parámetro a levantar es `enable_period`

**Comment by flaviaarias** [comment]
Se Agregó el campo enable_period y se bajó a un renglón más abajo la descripción del archivo seleccionado como foto o el error de carga del archivo para dejar espacio disponible para este nuevo campo

![Captura de pantalla de 2020-12-12 11-36-27.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/891eb561-4639-491f-9a16-d2df65e24255)
