### ISSUE TITLE
Estimacion de Cosecha y Analitica en InnovaFruit

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#677]
Todos los datos pedidos están en los formularios de datos de carga en GWMobile. 
La verdadera formula a calcular es la siguiente>

CÁLCULO DENOMINADO PRONÓSTICO DE COSECHA. Se calcula en 2 momentos: POST PODA Y POST RALEO

Corporación: InnovaFruit
Capas/Proyectos: Mediciones (`project_type_id = 12`) Y Variedad (`project_type_id = 2`)

Los datos capturados en campo con GWMobile se guardan en capa Mediciones de la siguiente manera: 

1) POST PODA (JULIO-AGOSTO)

Se realiza un cálculo PROMEDIO de las siguientes mediciones
a = mts lineales de poda por brazo  (Mediciones, campo 252, key: `mts_lineales_de_poda`)  

El promedio resultado SERÁN LOS METROS LINEALES POR BRAZO PROMEDIO DE LAS MEDICIONES Y se multiplica por lo siguiente:

c = Número de Frutos por Metro (Variedad, campo 217, key: `numero_de_frutos_por_metro`)
d = Peso Promedio del Fruto (gr) (Variedad, campo 209, key: `peso_promedio_del_fruto_gr`)

e = Prom (a) * c * d
Esto me da el peso promedio de frutos por BRAZO en POST PODA.

Luego, 
f = Número Brazos por hectárea (Variedad, campo 186, key: `nmero_brazos_por_hectrea`) 

g = PRONÓSTICO PODA POR HA(kg/ha) = e * f

Almacenar resultado en PRONÓSTICO PODA POR HA(kg/ha) (Variedad, campo 221, key: `pronstico_de_cosecha_en_hakgha`)

h= Superficie REAL (Variedad, campo 211, key: `superficie_real`)

PRONÓSTICO PODA POR VARIEDAD = g * h

Almacenar resultado en PRONÓSTICO RALEO POR VARIEDAD (kg/Variedad)  (Variedad, campo 222, key: `pronstico_cosecha_cuartel_kgvariedad_`)

2) POST RALEO

a = Promedio número frutos /brazo (Mediciones, sector post raleo, campo 270, key: `post_raleo_numero_de_frutosbrazo_unidad` (Post raleo número de frutos/brazo (unidad))
b = Número Brazos por hectárea (Variedad, campo 186, key: `nmero_brazos_por_hectrea`)  
c = Peso Estimado de Fruto en RALEO (gr) (Variedad, campo 228, key: `peso_estimado_de_fruto_en_raleo_gr`)

PRONÓSTICO RALEO POR HA (kg/HA)  Variedad, campo 226, key: `pronstico_cosecha_por_ha_kgha_`
d = a * b * c

Luego agregamos
e = Superficie REAL (Variedad, campo 211, key: `superficie_real`)

PRONÓSTICO RALEO POR VARIEDAD (kg/Variedad) (Variedad, campo 222, key: `pronstico_cosecha_cuartel_kgvariedad_` )

f = d * e

---

> De todas maneras tenes que tomar los valores de la Propiedad La Colina I. Las demas desestimalas
> En esta propiedad es donde estamos haciendo las muestras y ensayos

**Comment by jvillegas88** [comment]
Se generaron los indicadores y los gráficos solicitados:

![image](https://user-images.githubusercontent.com/36643035/107273622-10555600-6a2e-11eb-8b48-85ca1f1e7fec.png)

![image](https://user-images.githubusercontent.com/36643035/107273645-16e3cd80-6a2e-11eb-9140-96b50591dacc.png)
