### ISSUE TITLE
Clonar data de geoserver production y montarla en geoserver staging

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#691]
Se deployó geoworks en el servidor `staging` con un `dump` de los datos de `production`. Ahora es necesario clonar los datos de geoserver para poder ver las geometrías de estos datos.

Si se llega a poder armar un script automatice este proceso sería ideal así podemos mantener actualizado el server de staging aunque no es prioridad en este momento

Solicitar a Mariano los accesos ssh necesarios. La url para acceder al server de `staging` es (por ejemplo): http://tomate2000.st.geoworks.com.ar/es

**Comment by FelixPad** [comment]
GEOSERVER MIGRATION

Path en Linux: /var/lib/tomcat7/webapps/geoserver/data

En Docker container: # /opt/geoserver/data_dir
Volumen: #/var/lib/docker/volumes/<nombre del volumen>/_data

Copia de directorio “data”

$ scp -r felixp@geoworks.com.ar:/home/felixp/geoserver /c/Users/felix/Documents/GeoWorks/geoserver_migration/

Copia del directorio “data” al container de geoserver:

$ docker cp geoserver/data/ geoserver:/opt/geoserver

VOLUMEN: /var/lib/docker/volumes/<nombre del volumen>/_data

TOMCAT UI XML CONFIG

http://localhost:8600/manager/

./usr/local/tomcat/conf/tomcat-users.xml

*Error 403 al iniciar la aplicación geoserver desde la UI de Tomcat

Directorio de las aplicaciones web de Tomcat: aquí va el geoserver.war en versiones antiguas
/usr/local/tomcat/webapps

Aumentar límite de tamaño de subida en Tomcat
cd /path/to/tomcat
vim webapps/manager/WEB-INF/web.xml
<multipart-config>
   <max-file-size>52428800</max-file-size>
   <max-request-size>52428800</max-request-size>
   <file-size-threshold>0</file-size-threshold>
</multipart-config>
•	100 MB => 104857600

*NOTA: aparentemente Geonetwork necesita una version de Java 8 para funcionar.

Se necesita que la versión de Java sea la misma en ambos Geoserver.
Geoserver de producción 2.8.5 utiliza Java 7, para realizar una migración de "data" es necesario contar con otra versión de Geoserver con Java 7. 
La versión de Geoserver staging utiliza Java 11 por eso al iniciar Tomcat e iniciar Geoserver en Docker se obtiene un error 403.
