### ISSUE TITLE
ATRIBUTOS. Cuando guardo la edición de atributos el rol seleccionado no se muestra

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#73]
Ejemplo:

Seleccionamos los roles que pueden ver el atributo:
![image](https://user-images.githubusercontent.com/36643035/67503020-4f0aa580-f65d-11e9-8f8c-4c1b8e1fdb56.png)

Pero luego de guardar vuelve como sino estuvieran seleccionados:
![image](https://user-images.githubusercontent.com/36643035/67503154-81b49e00-f65d-11e9-90ba-462a75d0bb69.png)

**Comment by asergiop21** [comment]
Ahora se visualizan los roles seleccionados
