### ISSUE TITLE
Clonar datos de agq a agroterza

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#769]
Se necesita clonar el schema `agq` y restaurarlo en la corproación `agroterzabk`, ésta será una corporación intermedia que permitirá a Luis ajustar el modelo de datos para que quede igual al de `agroterza` actual. Todos los registros van a ingresar con el usuario `superadmin`. Luego se harán las reasignaciones a los usuarios correspondientes.

Una vez que la corporación `agroterzabk` esté lista, se intercambiarán los nombre de los schemas `agroterza` y `agroterzabk` para que `agroterza` contenga los datos del schema recién clonado y `agroterzabk` contenga un backup de los datos del `agroterza` actual

**Comment by FelixPad** [comment]
**La clonación del esquema AGQ a Agroterza se realizo mediante el proceso de pg_dump y psql restore**

Pasos seguidos para realizar el bkp y el restore:

1.  Dump en PGAdmin con format .sql, incluyendo predata, data y postdata o usando el comando pg_dump via shell.

2. Renombrar esquemas para la inserción de los datos:

ALTER SCHEMA agq RENAME TO agq1;

ALTER SCHEMA agroterzabk RENAME TO agq;

3. Restore:

psql -f agq_bk.sql geoworks

4. Renombrar esquemas a sus nombres de origen:

ALTER SCHEMA agq RENAME TO agroterzabk;

ALTER SCHEMA agq1 RENAME TO agq;

**Comment by jvillegas88** [comment]
Para concluir el clonado de la corporación también se hizo:

- Copiar los listados del viejo schema de agroterza al nuevo
- Eliminar las relaciones de los listados con los campos
- Eliminar gráficos, series e indicadores del nuevo agroterza
- Testear geoworks y sincronización con gwmobile
