### ISSUE TITLE
Corregir en la base de datos las semanas de baja del FSCDG

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#773]
Por un error de prototipeo se cargaron mal las semanas de baja de FSCDG en el proyecto Propiedades de la Corporación Tomate.
El campo que hay que modificar es el campo: "Semana Baja" id 481
Hay que reemplazar todos los valores de ese campo por la semana correspondiente a la semana del año que corresponde a la fecha del campo "FechaBaja" id 235
En caso de que el campo 235 no contenga datos, hay que eliminar también el dato del campo 481

**Comment by FelixPad** [comment]
Se buscaron los keys correspondientes a los campos Fecha Baja y Semana Baja.
Posteriormente se buscaron los datos

SELECT id, properties->>'fecha_baja_' FROM tomate2000.projects where properties->>'fecha_baja_' is not null
AND project_type_id = 5 ORDER BY id DESC;

SELECT id, properties->>'semana_baja' AS semana_baja, properties->>'fecha_baja_' AS fecha_baja FROM tomate2000.projects where properties->>'semana_baja' is not null
AND project_type_id = 5 ORDER BY id DESC;

Query ejemplo para extraccion de semana por id:
select p.id, p.properties->>'fecha_baja_' as fecha_baja, to_char(date '2020-01-01','YYYY-IW') as year, 
       extract('week' from date '2020-01-08') as week FROM tomate2000.projects p
	   where p.properties->>'fecha_baja_' is not null
      AND p.project_type_id = 5 AND id = 511;

--Datos mal cargados de "semana_baja" a null:
--nullear semana_baja
UPDATE tomate2000.projects
SET properties = jsonb_set(properties, '{semana_baja}', 'null')
WHERE properties ->> 'semana_baja' is not null returning id, properties ->> 'semana_baja' AS semana_baja, properties ->> 'fecha_baja_' AS fecha_baja;

Actualizacion
--update semana baja por id
UPDATE tomate2000.projects
SET properties = jsonb_set(properties, '{semana_baja}', '"2"', true)
WHERE id = 511 returning id, properties ->> 'semana_baja' AS semana_baja, properties ->> 'fecha_baja_' AS fecha_baja;

Actualizados los 13 registros de "semana_baja" existentes en "fecha_baja"

![image](https://user-images.githubusercontent.com/47112181/109257755-9a940d00-77d7-11eb-97cd-3d062aaadc1f.png)
