### ISSUE TITLE
Edicion de HIJOS. Campos calculados sin visualizacion y campos Opcion simple NO FUNCIONAN

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#924]
Tenemos un tema con un campo que se genera en gwmobile, corporacion Agroterza, en el proyecto cultivos, en el campo Identificación de Recomendación,  es un {id} calculado. Al ser hijo y un campo calculado entiendo que no se puede editar, pero, al menos debería poder verse. fijate que no se ven. 
Además, mismo todo en el campo Seguimiento de recomendación, es un combo con listados Anidados Se puede editar pero  no me toma los valores modificados por alguna razón y se cuelga. 
En listados de opción Simple si se puede editar, pero también se cuelga

**Comment by flaviaarias** [comment]
No es un bug es un tema de prototipeo. Estaba puesto como campo numérico y no lo es. 
Lo cambié a texto y ahora se ven. 
![Captura de pantalla de 2021-05-21 10-41-07](https://user-images.githubusercontent.com/54163342/119150173-923d1e00-ba24-11eb-82cc-148e766f38db.png)
![Captura de pantalla de 2021-05-21 10-41-36](https://user-images.githubusercontent.com/54163342/119150184-95380e80-ba24-11eb-9832-6b79d70829e5.png)

Los otros dos puntos tienen que ver con que no está terminada la Edición Web de hijos. El usuario superadmin no debería utilizarse para la edición de Hijos en Geoworks.
