### ISSUE TITLE
Limpieza db tomate2000 para presentación 11/06/21

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#951]
- [x] Mismos departamentos cargados de manera diferente:

```
SELECT DISTINCT properties ->> 'departamento', COUNT(*) 
FROM tomate2000.projects 
WHERE row_active = true
AND project_type_id IN (3,5)
AND properties ->> 'departamento' IS NOT null
GROUP BY properties ->> 'departamento' 
ORDER BY properties ->> 'departamento'
```

**"25 de Mayo"	46**
**"9 de Julio"	39**
"Angaco"	5
"Caucete"	26
"Chilecito"	115
"Guaymallén"	39
"Junín"	12
"Lavalle"	49
**"Luján"	7**
**"Luján de Cuyo"	15**
"Maipú"	70
**"Nueve de Julio"	7**
"Pocito"	474
"Rawson"	211
"Rivadavia"	26
"San Carlos"	149
"San Martín"	64
"San Rafael"	2
"Santa Rosa"	4
"Sarmiento"	7
"Tunuyán"	120
"Tupungato"	23
**"Veinticinco de Mayo"	11**

---

- [x] Mismas provincias cargadas de manera diferente:
```
SELECT DISTINCT properties ->> 'provincia', COUNT(*) 
FROM tomate2000.projects 
WHERE row_active = true
AND project_type_id IN (3,5)
AND properties ->> 'provincia' IS NOT null
GROUP BY properties ->> 'provincia' 
ORDER BY properties ->> 'provincia'
```

"La Rioja"	115
**"Mendoza"	560**
**"mza"	1**
"San Juan"	845

---

- [ ] Variedades cargadas con y sin corchetes. Unificar todo con corchetes.

```
SELECT DISTINCT properties ->> '63', COUNT (*)
FROM tomate2000.project_data_children
WHERE row_active = true
GROUP BY properties ->> '63' 
ORDER BY properties ->> '63' 
```
**["DOCET "]	1**
**DOCET 	7**
**Fokker**	8
**["Fokker"]	50**
["Heinz 1015"]	3
["Heinz 1178"]	2
["Heinz 1301"]	9
["Heinz 1307"]	5
**["HM 1892"]	128**
**HM 1892	13**
["HM 58871"]	5
["HM 7883"]	387
HM 7883	102
["ISI 22706"]	44
["ISI 23804"]	31
["Kendras"]	4
**["NUN 6416"]	4**
**NUN 6416	2**
**OTRAS	4**
**["OTRAS"]	23**
["STAR 9063"]	2

**Comment by flaviaarias** [comment]
La  provincia que estaba cargada como mza es el registro id=854 y tiene la columna row_seasson como false.
Se cambió en la base de datos

**Comment by flaviaarias** [comment]
Los Departamentos mal cargados que se corrigieron

![Captura de pantalla de 2021-06-09 14-44-52](https://user-images.githubusercontent.com/54163342/121404259-2a4a6b00-c932-11eb-91f3-55c0e4c26ce0.png)

![Captura de pantalla de 2021-06-09 14-04-18](https://user-images.githubusercontent.com/54163342/121404272-2dddf200-c932-11eb-86c4-e05fb44e90b9.png)

**Comment by flaviaarias** [comment]
Se corrigió la palabra Vivrocultivador
![Captura de pantalla de 2021-06-09 17-24-54](https://user-images.githubusercontent.com/54163342/121424453-bb780c80-c947-11eb-853a-2dcd979bb9ed.png)

![Captura de pantalla de 2021-06-09 17-25-23](https://user-images.githubusercontent.com/54163342/121424464-be72fd00-c947-11eb-9898-68cc0c86b883.png)

**Comment by flaviaarias** [comment]
Se ajustaron valores antiguos de listado Valoración de Estados para que se ajusten a los valores actuales

![Captura de pantalla de 2021-06-09 17-50-48](https://user-images.githubusercontent.com/54163342/121431725-24fc1900-c950-11eb-9e94-032fc89d19fd.png)
![Captura de pantalla de 2021-06-09 18-25-17](https://user-images.githubusercontent.com/54163342/121431729-288fa000-c950-11eb-825a-e34b548d088c.png)

**Comment by flaviaarias** [comment]
Ajuste de valores antiguos en listado de estado_equipo_de_pulverizacion
![Captura de pantalla de 2021-06-09 18-51-52](https://user-images.githubusercontent.com/54163342/121441744-c12e1c00-c960-11eb-8d63-fab1432084ee.png)

![Captura de pantalla de 2021-06-09 19-23-58](https://user-images.githubusercontent.com/54163342/121441755-c4290c80-c960-11eb-8a72-5d1bee50f1d9.png)

**Comment by flaviaarias** [comment]
Unificación de valores en listado de Valoración de Depósitos de Agroquímicos

![Uploading Captura de pantalla de 2021-06-09 20-40-10.png…]()

**Comment by flaviaarias** [comment]
Unificación de valores maquinas - Tractor Mediano 
![Captura de pantalla de 2021-06-09 21-10-50](https://user-images.githubusercontent.com/54163342/121445665-4a951c80-c968-11eb-8dec-d1796ab5a9e0.png)

**Comment by flaviaarias** [comment]
Unificación de valores Conservación de plantines
![Captura de pantalla de 2021-06-15 21-28-52.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/ee35ee25-a885-49f2-a6f5-da2634dad26f)

![Captura de pantalla de 2021-06-15 22-25-04.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/522431b0-b61b-47cb-9a28-ef6bf04a22bf)

**Comment by flaviaarias** [comment]
Limpieza de listado Valoración de la cama

![Captura de pantalla de 2021-06-15 22-30-00.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/44513aa0-2c61-4a5f-8eb5-40e24cff4434)

![Captura de pantalla de 2021-06-15 22-28-19.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/d51ba5de-4f9d-4acb-8019-3de5b1326098)

![Captura de pantalla de 2021-06-15 23-38-20.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/efb52f0d-d23b-47b4-9912-3c8611b3f84d)

**Comment by flaviaarias** [comment]
Limpieza listado valoración de transplante
![Captura de pantalla de 2021-06-15 23-42-55.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/1f6dfbe6-2135-4686-9f19-a0862735ef9b)![Captura de pantalla de 2021-06-15 23-40-27.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/74abd28e-fe38-4386-a844-4b4e2d6bee3c)

![Captura de pantalla de 2021-06-16 00-29-06.png](https://images.zenhubusercontent.com/5d78ef61ce6e6a000126f497/283e1819-f31c-420d-b19d-b9557dc28341)
