### ISSUE TITLE
Limpieza db iscamen para puesta a punto

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#954]
Tareas

- [x] Revisar si los hijos se están almacenando como array que contiene un objeto `[{}]` o como un objeto directamente `{}`. En el caso que estén como array se deben convertir a objetos todos los hijos.

- [x] Revisar si los listados utilizados en registros padres e hijos están almacenados como array `[]` o como string `""`. En el caso que estén como string se deberán convertir a un array que contenga ese string `[""]`

**Comment by LuchoAravena** [comment]
### **REGISTROS PADRES**
Se limpia base de datos de Iscamen, se adjunta detalles de los registros modificados: 

**id project_field: 370 (Area)
key: urbano
id listado: 26 (Area de mosca)
project_type: 14**

Urbana: 41
Rural: 7
No: 3174
Yes: 1362
False: 4
Finca: 2

Los registros como "no", "false" y "Finca" se actualizaron a "Rural"
Los registros como "yes" se actualizaron a "Urbana"

Urbana: 1403
Rural:  3187

Query de actualización:

UPDATE iscamen.projects
SET properties = jsonb_set(properties, '{urbano}', '["Rural"]', true)
WHERE project_type_id= 14 AND properties ->> 'urbano' ILIKE '%finca%' 
RETURNING properties ->> 'urbano', properties, id

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**id project_field: 657 (Conduccion)
key: conduccion
id listado: 11 (Conduccion)
project_type: 26**

Hay 1 registro cargado como: Id: 120682 | properties: “eje central”

-Se eliminó key y value 

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**id project_field: 366 (Delegacion)
key: oasis
id listado: 14 (Oasis 2)
project_type: 14**

Hay cargado registros como: ["A"], ["C"], ["E"], ["M"], ["N"], ["S"] que no corresponden al listado, se busca geometría de registro y se detecta lo siguiente:
["A"] = SUR - Gral. Alvear
["C"] = Centro
["E"] = Este
["M"] =  SUR - Malargüe
["N"] = Norte
["S"] = SUR - San Rafael

Se cambian los registros a los items antes mencionados: (Los ids modificados completos están en el documento "Ids registros cambiados "Oasis")

["A"]: 246 registros
["C"]: 1048 registros *
["E"]: 1041 registros 
["M"]: 28 registros  
["N"]: 1048 registros *
["S"]: 1124 registros 

*["Centro"] están estos ids ya cargados:
21662, 22665

*["Norte"] están estos ids ya cargados:
22408, 22523, 22249, 20007, 22158, 23338, 121614, 120726, 23112, 19864, 22450, 121577, 19024, 23299, 19038, 121616, 121615, 121617, 19686, 20220, 19449, 21102, 121623, 23043, 19103, 122301, 122302, 122303, 19222, 21344, 21716, 21807, 21902, 22103, 23424, 19236, 19649, 20120, 122287, 122288, 122304, 122305, 122306, 20063, 20539, 20956, 21438, 22518, 23122

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**id project_field: 369 (Ruta), 653 (Ruta)
key: ruta
Id listado: 6 (Ruta)
project_type: 26**

Verificar listado completo por registros cargados incorrectamente

-Se convierten los registros almacenados como number en array
-Se agregó ítem "88" a listado


-Se verifican que los registros almacenados coincidan con los item en listado (Ruta):
Hay 12 registros almacenados como ["88"] que no está en el listado

Registros como array      : 2848
                 como number : 733
(Después de update        : 3581 array)

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**id project_field: 371 (Hospedero Trampa)
key: hospederotrampa
id listado: 3 (Hospederos)
project_type: 14**

En el listado hay un ítem llamado “Otro” (sin “s” al final), en la base de datos hay 954 registros cargados como “Otros” (con “s” al final)

-Los registros cargados como "Otros" se modificaron a "Otro"

-Se eliminó key y value de registro almacenado como '0' (id 40111)

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**id project_field: 660 (Centro Trampeo)
key: centro_trampeo
id listado: 12 (Centro Trampeo)
project_type: 26**

Listado:
-Si
-No

Registros cargados:

"[""c 2512 n""]" : 1 reg. Id: 120676

"[""CENTRO""]" : 1 reg. Id: 120678

"[""Oasis Centro""]" : 2 reg. Id: 120686 y 120687

"[""OASIS CENTRO""]" : 2 reg. Id: 120668 y 120691

"[""tunuyan""]" : 1 reg. Id: 120682

"[""TUNUYAN""]" : 2 reg. Id: 120684 y 120679

Total: 9 registros

-Se eliminaron los registros mal cargados

Registros como "[]" se eliminaron también
ids: 
119636, 119640, 119645, 119638, 119623, 119651, 119644, 119627, 119643, 119652, 119649, 119641

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**ID project_field: 991 (Tipo trampa)
key: reingrese_tipo_trampa
Id listado: 7 (Tipo Trampa Mosca)
project_type: 14**

Listado:
-Jackson
-McPhail
-Otro

Hay un registro que está cargado como "Delta" que no coincide con el listado

-Se eliminó key y value de registro (No anoté id ja)

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**id project_field: 654 (Area)
key: area
id listado: 24 (Area de Trampeo)
project_type: 26**

Listado:
-Aeropuerto
-Bodega
-Empaque
-Finca
-Urbana
-Vivero

Hay registros cargados como:
-42
-43
-46
-51
-52
-87
-MonfarrelFinca

Se eliminaron registros cargados que correspondían a rutas de trampeo
ids: (19 registros en total)
119660, 119643, 120682, 120685, 120667, 120684, 119647, 120689, 120686, 120691, 120687, 120679, 120668, 120690, 120692, 120676, 119653, 119659, 119654

**Comment by LuchoAravena** [comment]
### **REGISTROS HIJOS**

**project_field id: 661 (Inspeccion)
id project_data_children: 60 (Reposición Insumos)
id listado: 17 (Reposicíon insumos)
project_type: 26**

-Cuerpo
-Cuerpo + Difusor
-Difusor
-Piso
-Piso + Cuerpo
-Piso + Difusor
-Revision sin reposiciones
-Trampa Completa

-1107 registros almacenados como “Sin Reposiciones” se modifican a “Revision sin reposiciones”

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**project_field id: 661 (Inspeccion)
id project_data_children: 85 (Motivos sin datos)
id listado: 21 (motivos sin datos)
project_type: 26**

-Cebo ausente - no activado
-Otra causa
-Piso ausente
-Trampa Ausente
-Trampa en suelo
-Trampa Instalada
-Trampa Vandalizada

"[""Aplicando insecticida""]"--- (35 registros)
Se modifican a "Otra causa" los ids: 296394, 298284, 298669, 305399, 305400, 305724, 305725, 307983, 308307, 309249, 309336, 309337, 309641, 312597, 314941, 315076, 315883, 309219, 298283, 302018, 304660, 307707, 309327, 309543, 309544, 314389, 314390, 314940, 314948, 315075, 317439, 320336, 320337, 304825, 299410

"[""Desinstalada""]"--- Se modifican a "Otra causa" (229 registros)

"[""TCS""]"--- Se modifican a "Otra causa" (680 registros)

"[""Trampa rota""]"--- (21 registros)
Se modifican a "Otra causa" los ids: 294300, 294301, 294382, 294383, 305723, 309697, 309698, 317010, 317011, 317617, 317618, 317619, 318410, 318411, 322454, 323614, 323615, 324701, 317616, 322453, 325750

-1026 registros almacenados como "Trampa instalada" se modifican a "Trampa Instalada"

-----------------------------------------------------------------------------------------------------------------------------------------------------------
**project_field id: 661 (Inspeccion)
id project_data_children: 83 (Motivos innaccesiblidad)
id listado: 20 (innaccesibilidad a trampas)
project_type: 26**

lo mismo que en motivos sin datos

Listado: 
-Animales peligrosos
-Camino cortado – inundado
-Otra causa
-Parcela inundada
-Permiso no otorgado
-Rotura de vehículo
-Tranquera cerrada

Hay registros guardados como:

"[""Feriado""]"--- Se cambiaron a "Otra causa" (63 registros)
"[""Otras actividades asignadas""]"--- Se cambiaron a "Otra causa" (92 registros)


-45 registros almacenados como “Tranquera cerrada” se modifican a “Tranquera Cerrada”: 
290804, 294730, 294731, 295863, 295864, 296266, 296267, 297586, 297813, 297814, 300520, 300521, 300617, 306333, 306334, 306353, 306354, 309364, 314874, 314875, 316481, 316482, 316634, 316885, 316886, 317684, 317685, 317988, 317989, 320054, 320055, 321084, 321987, 321988, 325389, 325390, 325996, 325997, 326200, 326201, 314059, 316633, 290803, 295871, 295872

**Comment by LuchoAravena** [comment]
### **MODIFICACION REGISTROS PADRES**

Guardo IDs registros '["null"]' para luego eliminar registros: pf* (project_field)

**project_type = 14** 

pf otros_hospederos, 
modificados: 20730 ["null"]
modificados: 40111 '[]'

pf hospederotrampa
modificados: 102565 '[]'

--------------------------------------------------------------------------------------------------------------------
**project_type = 26**

pf activa,
modificados: 119627, 119649, 119641, 119638, 119640, 119623, 119636, 119645, 119652, 119644, 119651, 119643 '[]'

pf centro_trampeo,
Todos nulos (2494 registros)

pf programa
modificados: 119649, 119638, 119645, 119644, 119651 '[]'

pf tipo_trampa
modificados: 119649, 119638, 119645, 119644, 119651, 119643  '[]'

pf tipo_cebo
modificados: 119649, 119638, 119645, 119644, 119651, 119643 '[]'

pf delegacion
modificados: 119649, 119638, 119645, 119644, 119651, 119643  '[]'

pf oasis
modificados: 118928, 116934, 118107, 116561, 115461, 115856, 117802, 115702, 115834, 118104, 119352, 117933, 117610, 117473, 117598, 116759, 119010, 116993, 116992, 118111, 115709, 115873, 115855, 118083  '["null"]'
modificados: 119649, 119638, 119645, 119644, 119651, 119643 '[]'


pf ruta
modificados: (2486 registros) '["null"]'
modificados: 119649, 119641, 119638, 119645, 119644, 119651, 119643  '[]'


pf red
modificados: (2493 registros) '["null"]
modificados:  119627, 119649, 119638, 119640, 119623, 119636, 119645, 119652, 119644, 119651, 119643, 119641  '[]'


pf area
modificados: (1198 registros) '["null"]'

pf hospedero
modificados: (1198 registros) '["null"]'
modificados: 119649, 119638, 119645, 119644, 119651, 119643, 119641  '[]'

pf variedades
modificados: (2522 registros) '["null"]'
modificados: 119649, 119638, 119645, 119644, 119651, 119643, 119641  '[]'

pf conduccion
modificados: (1837 registros) '["null"]'
modificados: 119649, 119638, 119636, 119645, 119644, 119651, 119643, 119641 '[]'

**Comment by LuchoAravena** [comment]
-Revisar si los listados utilizados en registros padres e hijos están almacenados como array [] o como string "". En el caso que estén como string se deberán convertir a un array que contenga ese string [""]

**Se convirtieron los registros almacenados como strings en arrays**

Id 370
Padre: Area, Key: urbano.  4 booleano

Id 367
Padre: Oasis, Key: oasis.  1177 null / También está en Project 26, Id: 651 / También está en Project 49, Id: 1123. 1177 null

Id 368
Padre: Red, Key: red.  1790 null / También está en Project: 26, Id: 652

Id 369
Padre: Ruta, Key: ruta.  1791 null / También está en Project: 26, Id: 653

Id 366
Padre: Delegacion, Key: delegacion.  2 null / También está en Project: 26, Id: 650

Id 371
Padre: Hospedero trampa. Key: hospederotrampa. 53 null
---------------------------------------------------------------------------------------------------
Project: 26

Id 660
Padre: Centro Trampeo. Key: centro_trampeo. 1768 null

Id 642
Padre: Programa, Key: programa. 1 null

IDs: 123, 125

-Query utilizado: 
Para búsqueda de tipo de registro:

WITH jsontypes AS (
    SELECT
        properties.key AS key1,
        jsonb_typeof(properties.value) AS jsontype
    FROM iscamen.projects, jsonb_each(iscamen.projects.properties) AS properties
	WHERE project_type_id = 8
)
SELECT *, COUNT(*)
FROM jsontypes
WHERE key1 = 'temporada'
GROUP BY key1, jsontype
ORDER BY key1, jsontype;


Para actualización de registros: 

UPDATE iscamen.project
SET properties = jsonb_set(
properties,
ARRAY['ruta'],
to_jsonb(string_to_array(REPLACE((properties->'ruta')::text, '"',''), ';'))
)
WHERE jsonb_typeof(properties->'ruta') = 'number' AND project_field_id = 26 AND row_active = true
RETURNING properties, update_sequence;
