### ISSUE TITLE
Agregar datastore y publicar capas en geoserver para la corporación Agrovants

### ISSUE THREAD

**Issue by JChambu** [JChambu/geoworks#975]
Quizás tengan que hacer una actualización en el geoserver de Agrovants, porque importo bien un archivo GeoJson pero no me muestra los polígonos importados.

**Comment by jvillegas88** [comment]
Se creó el almacén de datos `agrovants` y se publicaron todas las capas que estaban disponibles

![image](https://user-images.githubusercontent.com/36643035/122613550-692b9f80-d05b-11eb-8170-e25e88dc0886.png)
