### ISSUE TITLE
Agregar permisos para descargar reportes XLS y GeoJSON

### ISSUE THREAD

**Issue by flaviaarias** [JChambu/geoworks#995]

**Comment by jvillegas88** [comment]
Para asignar permisos para exportar datos tanto en XLS como en PDF se deberá hacer desde la opcion **Exportar** del módulo **Datos**:

![Captura de pantalla de 2021-09-10 18-41-28](https://user-images.githubusercontent.com/36643035/132920660-50d7fe6d-386e-45f0-a0c5-e19b598da729.png)
